WIKI.paper({
slug:'evalplus',
venue:'NeurIPS 2023',
authors:'Liu, Xia, Wang, Zhang (University of Illinois Urbana-Champaign · Nanjing University)',
arxiv:'2305.01210',

tldr:'[HumanEval](#/p/humaneval)의 테스트 케이스가 너무 부실해서 **틀린 코드도 통과시킨다**는 사실을 밝히고, 테스트를 자동으로 80배 늘린 HumanEval+를 만들었다. 늘어난 테스트로 다시 채점하자 26개 LLM의 pass@k가 최대 19.3~28.9%p 떨어지고, 심지어 모델 간 순위까지 뒤바뀌었다.',

context:'2023년 코드 생성 LLM 평가는 사실상 [HumanEval](#/p/humaneval)의 pass@k 점수로 수렴해 있었다. 그런데 HumanEval의 164개 문제는 문제당 평균 테스트가 **9.6개**에 불과하다. 문제는 함수가 처리해야 할 입력의 경우의 수가 그보다 훨씬 많다는 것 — 몇 개의 대표 입력만 통과하면 실제로는 틀린 로직도 정답 처리된다. 저자들은 "ChatGPT가 생성한 코드가 정말로 맞는가"라는 단순한 질문에서 출발해, 벤치마크 자체의 테스트 커버리지를 의심했다.',

ideas:[
 {h:'LLM 시드 + type-aware mutation으로 테스트를 자동 증식',
  lead:'ChatGPT로 고품질 시드 입력을 만들고, 타입별 변이 규칙으로 대량 증식한다.',
  d:'먼저 정답 구현과 기존 입력 예시를 프롬프트에 넣어 ChatGPT에게 "복잡한/까다로운/코너케이스 입력"을 만들게 한다. 이 시드를 출발점으로 `int`는 $\\pm1$, `str`은 부분열 삽입/삭제/치환, `list`/`dict`는 원소 단위 변형처럼 **타입별 변이 규칙**(Table 1)을 적용해 입력 풀을 계속 불린다. 순수 LLM 생성만으로는 느리고 비싸서, 값싼 변이 연산으로 규모를 키우는 하이브리드 구조다.'},
 {h:'차분 테스팅으로 오라클 문제를 피한다',
  lead:'정답 구현의 출력과 LLM 코드의 출력을 직접 비교해 정오를 판정한다.',
  d:'새로 생성한 입력에 대해 "정답이 무엇인가"를 사람이 일일이 라벨링할 필요가 없다. 데이터셋에 원래 포함된 ground-truth 구현에 새 입력을 넣어 나온 출력을 오라클로 삼고, LLM이 낸 코드의 출력과 비교하는 **differential testing**만으로 대량의 새 테스트를 값싸게 검증한다.'},
 {h:'프로그램 계약으로 잘못된 입력을 걸러낸다',
  lead:'`assert n > 0` 같은 사전조건 주석으로 변이 생성 입력의 유효성을 보장한다.',
  d:'자동 생성/변이된 입력 중에는 함수가 애초에 정의되지 않은 영역(예: 음수 인덱스)이 섞일 수 있다. 문제마다 사전조건을 코드 assertion 형태로 달아, 그 조건을 어기는 입력은 생성 단계에서 걸러 미정의 동작으로 인한 오탐을 막는다.'},
 {h:'Test-suite reduction: 늘린 테스트를 다시 압축',
  lead:'greedy set cover로 커버리지·mutation kill 효과를 유지하며 테스트 수를 줄인다.',
  d:'문제당 평균 764.1개까지 불어난 테스트는 그대로 쓰면 평가 비용이 크다. 커버리지·mutation testing 결과·실제 LLM 오답 검출력을 그대로 유지하는 최소 부분집합을 greedy set cover로 뽑아 **HumanEval+-Mini**(평균 16.1개, 47배 축소)를 만들고도 판별력이 거의 유지됨을 보였다.'}
],

diagram:{type:'flow', cap:'EvalPlus 파이프라인. 원본 데이터셋의 정답 구현과 소수 입력에서 시작해, LLM과 변이를 섞어 테스트를 대량 증식한 뒤 differential testing으로 채점한다.',
 nodes:[
  {t:'원본 시드 입력', s:'HumanEval 평균 9.6개'},
  {t:'ChatGPT 시드 생성', s:'복잡·코너케이스 유도'},
  {t:'type-aware 변이', s:'타입별 규칙 반복 적용', acc:true},
  {t:'테스트 축소', s:'greedy set cover'},
  {t:'차분 테스팅', s:'f(x) = gt(x)?'}
 ]},

math:[
 {expr:'f(x) = gt(x)?',
  tex:'f(x) \\stackrel{?}{=} \\text{gt}(x)',
  d:'차분 테스팅의 판정식. LLM이 낸 함수 $f$ 와 데이터셋의 ground-truth 구현 $gt$ 에 같은 입력 $x$ 를 넣어 출력이 같은지만 비교한다 — 사람이 정답을 새로 라벨링할 필요가 없다.'}
],

numbers:[
 {k:'테스트 케이스 증가', v:'평균 9.6개 → 764.1개', d:'HumanEval → HumanEval+, 약 80배(Table 2)'},
 {k:'평가 모델 수', v:'26개 LLM', d:'[GPT-4](#/p/gpt4)·ChatGPT·WizardCoder-CodeLlama·Phind-CodeLlama·CodeLlama 등'},
 {k:'pass@k 하락폭', v:'최대 19.3~28.9%p', d:'k값에 따라 HumanEval 대비 HumanEval+에서의 하락 범위'},
 {k:'GPT-4 pass@1(greedy)', v:'88.4 → 76.2', d:'HumanEval 대비 HumanEval+에서 약 12%p 하락(Table 3)'},
 {k:'HumanEval+-Mini 축소율', v:'47배(평균 16.1개)', d:'test-suite reduction 후에도 판별력 유지'},
 {k:'순위 역전', v:'WizardCoder·Phind-CodeLlama > ChatGPT', d:'HumanEval에서는 ChatGPT보다 못했지만 HumanEval+에서는 앞섬'}
],

impact:'"벤치마크 숫자를 그대로 믿지 말라"는 태도를 코드 생성 평가에 정착시켰다. HumanEval+는 이후 코드 LLM 논문들이 [HumanEval](#/p/humaneval) 단독 대신 나란히 보고하는 사실상의 짝 벤치마크가 됐고, 저자들이 발견한 **순위 역전**(테스트가 약할 때는 안 보이던 모델 간 우열이 테스트를 강화하자 드러남)은 이후 다른 벤치마크(수학·추론)에서도 "테스트가 약하면 순위 자체가 왜곡될 수 있다"는 경계심을 낳았다. 부수적으로 HumanEval의 **정답 구현 자체에 오류**가 있다는 점도 함께 지적했다.',

legacy:[
 '**HumanEval+ / MBPP+**가 코드 생성 리더보드의 표준 짝 지표로 자리잡음',
 '**test-suite reduction(greedy set cover)** 아이디어가 이후 다른 대규모 테스트 자동 생성 연구에 재사용됨',
 '"벤치마크의 테스트 부실이 순위를 왜곡한다"는 이 논문의 발견이 다른 도메인(수학·에이전트) 벤치마크 재검증 흐름에도 영향',
 '오픈소스 프레임워크(evalplus)가 이후 다른 코드 LLM 평가 파이프라인에 그대로 채택됨'
],

pitfalls:[
 '**"HumanEval 통과율이 높다 = 코드가 옳다"가 아니다.** 이 논문이 보인 pass@k 하락폭은 기존 테스트가 놓치던 오답이 그만큼 많았다는 뜻이다.',
 '**순위 역전은 항상 일어나는 게 아니라 사례로 보고된 것이다.** WizardCoder-CodeLlama·Phind-CodeLlama vs ChatGPT의 역전이 대표 사례지 모든 모델 쌍에서 순위가 바뀌는 것은 아니다.',
 '**테스트를 늘렸다고 완전한 정답 판정은 아니다.** differential testing은 어디까지나 ground-truth 구현과의 입출력 일치를 보는 것이라, ground-truth 자체가 틀렸을 가능성(논문이 실제로 발견한 사례)은 별도로 남는다.'
],

figures:[
 {f:'fig1-overview.png',
  cap:'왼쪽 위 ChatGPT가 원본 데이터셋의 정답 구현과 기존 입력을 보고 시드 입력을 만들고, type-aware mutation이 이를 계속 변형해 seed pool을 채운다. 아래 differential testing 상자가 LLM이 낸 함수 f와 정답 gt에 같은 입력 x를 넣어 f(x)=gt(x)인지 비교해 통과/실패를 가른다. 오른쪽 위 Test-suite Reduction은 늘어난 테스트를 greedy set cover로 다시 압축하는 단계.',
  src:'원문 Figure 2, p.3'}
],

quotes:[
 {t:'Our extensive evaluation over 26 popular LLMs surprisingly finds that the pass@k on the new dataset is up-to 19.3-28.9% (for different ks) lower than the base HumanEval.',
  src:'Section 2, p.3'}
],

links:[
 {t:'arXiv 2305.01210 — Is Your Code Generated by ChatGPT Really Correct?', u:'https://arxiv.org/abs/2305.01210'},
 {t:'EvalPlus GitHub', u:'https://github.com/evalplus/evalplus'}
]
});
