/* ===== 개념 사전 =====================================================
 * 논문 계보만으로는 "temperature 가 뭔가" 에 답할 수 없다. 이 파일은
 * 인공지능 개발자가 알아야 하는 개념·용어를 따로 모은 색인이다.
 *
 * 행 형식: [slug, 영문 표기, 한국어, 그룹, 난이도(1~3), 관련 논문 slug[]]
 * 관련 논문은 content/fields.js 의 WIKI.INDEX 슬러그를 가리킨다.
 * 개념 본문은 content/concepts/<slug>.js 에 WIKI.concept({...}) 로 둔다.
 * ==================================================================== */

WIKI.CONCEPT_GROUPS = [
  { id:'basic', name:'기초', desc:'무엇을 배우고 어떻게 배우는가 — 모든 모델이 공유하는 바닥.' },
  { id:'arch',  name:'구조', desc:'CNN·RNN·Transformer 를 이루는 부품들.' },
  { id:'train', name:'학습 방법', desc:'사전학습·미세조정·증류·강화학습처럼 "어떻게 학습시키는가".' },
  { id:'optim', name:'옵티마이저', desc:'경사를 어떤 방식으로 가중치에 반영하는가.' },
  { id:'gen',   name:'생성과 추론', desc:'LLM 을 실제로 쓸 때 만나는 것들 — 토큰·샘플링·캐시·환각.' },
  { id:'eval',  name:'평가와 실무', desc:'숫자를 어떻게 읽고 무엇을 의심해야 하는가.' },
  { id:'math',  name:'수학 기초', desc:'선형대수·미적분·확률 — 논문의 수식을 읽으려면 필요한 최소한.' },
  { id:'classic', name:'고전 기계학습', desc:'딥러닝 이전이자 지금도 현역. 표 데이터에서는 여전히 이쪽이 강하다.' },
  { id:'data',  name:'데이터 다루기', desc:'모델보다 데이터가 성능을 더 많이 좌우한다.' },
  { id:'cv',    name:'컴퓨터 비전 실무', desc:'검출·분할을 실제로 돌릴 때 쓰는 말들.' },
  { id:'nlp',   name:'자연어 처리', desc:'언어모델 이전부터 이어지는 NLP 의 기본 어휘.' },
  { id:'llmops',name:'LLM 실무', desc:'API 를 쓰든 직접 띄우든, LLM 을 제품에 넣을 때 만나는 것들.' },
  { id:'genmodel', name:'생성 모델', desc:'오토인코더·GAN·확산모델의 개념과 그 안의 손잡이들.' },
  { id:'rlc',   name:'강화학습', desc:'보상으로 배우는 방식의 기본 어휘 — RLHF 를 이해하려면 필요하다.' },
  { id:'mlops', name:'MLOps · 운영', desc:'학습이 끝난 뒤가 진짜 시작이다.' }
];

WIKI.CONCEPTS = [
['perceptron-c','Perceptron','퍼셉트론','basic',1,['perceptron','backprop']],
['activation','Activation Function','활성 함수','basic',1,['gelu','swish','elu']],
['loss-function','Loss Function','손실 함수','basic',1,['focal-loss','giou']],
['gradient-descent','Gradient Descent','경사 하강법','basic',1,['backprop','adam']],
['backprop-c','Backpropagation','역전파','basic',1,['backprop']],
['overfitting','Overfitting','과적합','basic',1,['dropout','rethinking-generalization']],
['regularization','Regularization','정칙화','basic',1,['dropout','adamw','cutout']],
['normalization','Normalization','정규화 층','basic',2,['batchnorm','layernorm','instance-norm']],
['batch-epoch','Batch · Epoch · Iteration','배치 · 에폭 · 이터레이션','basic',1,['lr-scaling']],
['learning-rate','Learning Rate','학습률','basic',1,['sgdr','lr-scaling','adam']],
['bias-variance','Bias-Variance Tradeoff','편향-분산 트레이드오프','basic',2,['double-descent']],
['generalization','Generalization','일반화','basic',2,['rethinking-generalization','double-descent']],
['train-val-test','Train · Validation · Test','학습 · 검증 · 시험 분할','basic',1,['imagenet-v2','cifar-10-v2']],
['gradient-problem','Vanishing · Exploding Gradient','경사 소실 · 폭주','basic',2,['lstm','resnet','batchnorm']],
['cnn','Convolutional Neural Network','CNN 합성곱 신경망','arch',1,['lenet','alexnet','resnet']],
['convolution','Convolution · Kernel · Stride · Padding','합성곱 · 커널 · 스트라이드 · 패딩','arch',1,['lenet','vgg','deeplab']],
['pooling','Pooling','풀링','arch',1,['lenet','vgg']],
['receptive-field','Receptive Field','수용 영역','arch',2,['vgg','deeplab','segformer']],
['rnn','Recurrent Neural Network','RNN 순환 신경망','arch',1,['lstm','seq2seq']],
['lstm-c','LSTM','LSTM 장단기 메모리','arch',1,['lstm','gru']],
['attention-c','Attention','어텐션','arch',1,['bahdanau','transformer']],
['self-attention','Self-Attention','셀프 어텐션','arch',1,['transformer','sparse-attn']],
['multi-head','Multi-Head Attention','멀티헤드 어텐션','arch',2,['transformer','mqa','gqa']],
['transformer-block','Transformer Block','트랜스포머 블록','arch',1,['transformer','layernorm']],
['positional-encoding','Positional Encoding','위치 인코딩','arch',2,['transformer','rope','alibi']],
['residual','Residual Connection','잔차 연결','arch',1,['resnet','transformer']],
['encoder-decoder','Encoder · Decoder','인코더 · 디코더','arch',1,['seq2seq','transformer','bert','gpt1']],
['embedding','Embedding','임베딩','arch',1,['word2vec','glove','sentence-bert']],
['moe','Mixture of Experts','전문가 혼합(MoE)','arch',2,['moe-shazeer','switch','deepseek-moe']],
['supervision-types','Supervised · Unsupervised · Self-Supervised','지도 · 비지도 · 자기지도','train',1,['simclr','bert','mae']],
['transfer-learning','Transfer Learning','전이 학습','train',1,['bit','imagenet','dann']],
['pretrain-finetune','Pre-training · Fine-tuning','사전학습 · 미세조정','train',1,['bert','gpt1','flan']],
['distillation-c','Knowledge Distillation','지식 증류','train',2,['distillation','distilbert','mobile-sam']],
['quantization','Quantization','양자화','train',2,['llm-int8','gptq','bitnet']],
['pruning','Pruning','가지치기','train',2,['deep-compression','lottery-ticket']],
['augmentation','Data Augmentation','데이터 증강','train',1,['cutout','cutmix','randaugment']],
['contrastive','Contrastive Learning','대조 학습','train',2,['simclr','moco','clip']],
['rl-basics','Reinforcement Learning Basics','강화학습 기본 개념','train',1,['dqn','ppo','trpo']],
['rlhf','RLHF','사람 피드백 강화학습','train',2,['instructgpt','dpo','summarize-hf']],
['peft','PEFT · LoRA','파라미터 효율 미세조정','train',2,['lora','adapter','prefix-tuning']],
['few-shot','Zero-shot · Few-shot · In-context Learning','제로샷 · 퓨샷 · 문맥 내 학습','train',1,['gpt3','good-in-context']],
['sgd','SGD','확률적 경사 하강','optim',1,['adam','lr-scaling']],
['momentum','Momentum · Nesterov','모멘텀','optim',2,['adam','lion']],
['adaptive-optimizer','AdaGrad · RMSProp · Adam','적응적 옵티마이저','optim',2,['adam','adadelta','adafactor']],
['adamw-c','Weight Decay · AdamW','가중치 감쇠와 AdamW','optim',2,['adamw','adam']],
['lr-schedule','Learning Rate Schedule · Warmup','학습률 스케줄과 워밍업','optim',2,['sgdr','lr-scaling']],
['optimizer-choice','Which Optimizer to Use','옵티마이저 고르기','optim',2,['adamw','lion','sophia','adafactor']],
['tokenizer','Tokenizer','토크나이저','gen',1,['bpe','sentencepiece','unigram-lm']],
['token','Token','토큰','gen',1,['bpe','gpt3']],
['context-window','Context Window','컨텍스트 윈도우','gen',1,['longrope','yarn','streaming-llm']],
['sampling','Sampling','샘플링','gen',1,['nucleus-sampling','gpt2']],
['temperature','Temperature','temperature','gen',1,['nucleus-sampling','temperature-scaling']],
['top-k-top-p','Top-k · Top-p','Top-k · Top-p','gen',1,['nucleus-sampling']],
['beam-search','Beam Search','빔 서치','gen',2,['seq2seq','nucleus-sampling']],
['kv-cache','KV Cache','KV 캐시','gen',2,['vllm','h2o','mqa']],
['perplexity','Perplexity','퍼플렉시티','gen',2,['gpt2','scaling-laws']],
['hallucination','Hallucination','환각','gen',1,['rag','self-rag','nougat']],
['prompt-engineering','Prompt Engineering','프롬프트 엔지니어링','gen',1,['gpt3','prompt-survey','cot']],
['cot-c','Chain of Thought','사고 사슬(CoT)','gen',1,['cot','zero-shot-cot','self-consistency']],
['rag-c','RAG','검색 증강 생성','gen',1,['rag','dpr','hyde']],
['speculative','Speculative Decoding','추측 디코딩','gen',3,['speculative','eagle','medusa']],
['diffusion-basics','Diffusion Model','확산 모델 기초','gen',2,['ddpm','ldm','cfg']],
['guidance','Classifier-Free Guidance','분류기 없는 유도','gen',3,['cfg','ldm']],
['precision-recall','Accuracy · Precision · Recall · F1','정확도 · 정밀도 · 재현율 · F1','eval',1,['msp-baseline','chexnet']],
['confusion-matrix','Confusion Matrix','혼동 행렬','eval',1,['chexnet']],
['auroc','AUROC · AUPR','AUROC · AUPR','eval',2,['msp-baseline','odin']],
['iou-map','IoU · mAP','IoU · mAP','eval',1,['giou','yolov3','coco-captions']],
['bleu-rouge','BLEU · ROUGE','BLEU · ROUGE','eval',2,['seq2seq','pointer-generator','rl-summarization']],
['fid-is','FID · Inception Score','FID · Inception Score','eval',2,['fid','improved-gan','inception-score-note']],
['calibration','Calibration · ECE','보정과 ECE','eval',2,['temperature-scaling','deep-ensembles']],
['data-leakage','Data Leakage · Contamination','데이터 누수와 오염','eval',2,['livecodebench','catboost']],
['ablation','Ablation Study','절제 실험','eval',1,['yolov4','ft-transformer']],
['benchmark-pitfall','Reading Benchmarks Correctly','벤치마크 바로 읽기','eval',2,['imagenet-v2','mmlu-pro','trees-still-win']],
['vector-matrix','Vector · Matrix · Dot Product','벡터 · 행렬 · 내적','math',1,['backprop']],
['tensor','Tensor','텐서','math',1,['tensorflow']],
['matmul','Matrix Multiplication','행렬 곱','math',1,['transformer','flashattention']],
['derivative','Derivative · Partial Derivative · Chain Rule','미분 · 편미분 · 연쇄 법칙','math',1,['backprop']],
['jacobian-hessian','Jacobian · Hessian','야코비안 · 헤세 행렬','math',3,['sophia','adam']],
['probability-dist','Probability Distribution','확률 분포','math',1,['vae','gpt3']],
['bayes','Conditional Probability · Bayes Rule','조건부 확률 · 베이즈 정리','math',2,['mc-dropout','deep-ensembles']],
['expectation-variance','Expectation · Variance','기대값 · 분산','math',1,['batchnorm','gae']],
['entropy-kl','Entropy · Cross-Entropy · KL Divergence','엔트로피 · 교차 엔트로피 · KL 발산','math',2,['vae','instructgpt','tent']],
['mle','Maximum Likelihood Estimation','최대우도추정','math',2,['vae','nnlm']],
['norm','Norm · L1 · L2','노름','math',2,['adamw','deep-compression']],
['eigen-svd','Eigenvalue · SVD','고윳값 · 특이값 분해','math',3,['lora','vqvae']],
['convexity','Convexity · Local Minima · Saddle Point','볼록성 · 지역 최솟값 · 안장점','math',2,['adam','sgdr']],
['curse-dimensionality','Curse of Dimensionality','차원의 저주','math',2,['faiss','hnsw']],
['monte-carlo','Monte Carlo · Sampling','몬테카를로 · 표본추출','math',2,['mc-dropout','muzero']],
['supervised-tasks','Classification · Regression','분류와 회귀','classic',1,['lenet','xgboost']],
['linear-regression','Linear Regression','선형 회귀','classic',1,['backprop']],
['logistic-regression','Logistic Regression','로지스틱 회귀','classic',1,['perceptron']],
['svm-c','Support Vector Machine','서포트 벡터 머신','classic',2,['alexnet']],
['decision-tree','Decision Tree','결정 트리','classic',1,['xgboost','catboost']],
['random-forest-c','Random Forest · Bagging','랜덤 포레스트 · 배깅','classic',2,['xgboost','trees-still-win']],
['boosting','Boosting · GBM','부스팅','classic',2,['xgboost','lightgbm','catboost']],
['knn','k-Nearest Neighbors','k-최근접 이웃','classic',1,['faiss','prototypical']],
['kmeans-c','k-Means Clustering','k-평균 군집','classic',1,['vqvae','patchcore']],
['pca-c','PCA','주성분 분석','classic',2,['vqvae']],
['tsne-umap','t-SNE · UMAP','t-SNE · UMAP','classic',2,['word2vec','item2vec']],
['naive-bayes','Naive Bayes','나이브 베이즈','classic',1,['bm25']],
['ensemble','Ensemble · Bagging · Boosting · Stacking','앙상블','classic',2,['deep-ensembles','xgboost']],
['hmm-crf','HMM · CRF','은닉 마르코프 모형 · CRF','classic',3,['ctc','deeplab']],
['mlp','Multilayer Perceptron','다층 퍼셉트론(MLP)','basic',1,['perceptron','backprop']],
['weight-init','Weight Initialization','가중치 초기화','basic',2,['resnet','batchnorm']],
['dropout-c','Dropout','드롭아웃','basic',1,['dropout','mc-dropout']],
['softmax','Softmax · Logit','소프트맥스와 로짓','basic',1,['transformer','temperature-scaling']],
['one-hot','One-Hot Encoding','원-핫 인코딩','basic',1,['word2vec']],
['grad-clipping','Gradient Clipping','경사 클리핑','basic',2,['lstm','ppo']],
['mixed-precision-c','Mixed Precision · FP16 · BF16','혼합 정밀도','basic',2,['mixed-precision','fp8']],
['checkpointing','Gradient Checkpointing','경사 체크포인팅','basic',3,['zero','fsdp']],
['param-count','Parameter Count · FLOPs · Memory','파라미터 수 · FLOPs · 메모리','basic',2,['scaling-laws','chinchilla']],
['dataset-dataloader','Dataset · DataLoader · Collate','데이터셋과 데이터로더','data',1,['imagenet']],
['labeling','Labeling · Annotation','라벨링','data',1,['imagenet','sam']],
['class-imbalance','Class Imbalance','클래스 불균형','data',2,['focal-loss','msp-baseline']],
['feature-engineering','Feature Engineering','특징 공학','data',2,['xgboost','trees-still-win']],
['scaling-features','Feature Scaling · Standardization','특징 스케일링','data',1,['batchnorm']],
['stratified-split','Stratified Split · Grouped Split','층화 분할 · 그룹 분할','data',2,['cifar-10-v2']],
['synthetic-data','Synthetic Data','합성 데이터','data',2,['real-esrgan','phi-textbooks','unnatural-instructions']],
['data-quality','Data Quality · Deduplication','데이터 품질과 중복 제거','data',2,['fineweb','the-pile','quantify-memorization']],
['data-versioning','Data Versioning · Reproducibility','데이터 버전 관리와 재현성','data',2,['nnunet']],
['bbox-nms','Bounding Box · Anchor · NMS','바운딩 박스 · 앵커 · NMS','cv',1,['faster-rcnn','yolov3','diou']],
['seg-types','Semantic · Instance · Panoptic Segmentation','분할의 세 종류','cv',1,['fcn','mask-rcnn','panoptic']],
['backbone-neck-head','Backbone · Neck · Head','백본 · 넥 · 헤드','cv',1,['resnet','fpn','yolov3']],
['image-preprocess','Image Preprocessing · Resize · Normalize','이미지 전처리','cv',1,['alexnet','vit']],
['color-space','Color Space · Channel','색공간과 채널','cv',1,['alexnet']],
['anchor-free','Anchor-based vs Anchor-free','앵커 기반 vs 앵커 프리','cv',2,['fcos','centernet','detr']],
['multi-scale','Multi-Scale · Feature Pyramid','다중 스케일과 특징 피라미드','cv',2,['fpn','efficientdet']],
['deploy-onnx','ONNX · TensorRT · Deployment','ONNX · TensorRT 배포','cv',2,['mobilenetv2','rtmpose']],
['language-model','Language Model','언어 모델이란','nlp',1,['nnlm','gpt2']],
['ngram','n-gram','n-그램','nlp',1,['nnlm','bm25']],
['static-vs-contextual','Static vs Contextual Embedding','정적 임베딩 vs 문맥 임베딩','nlp',2,['word2vec','elmo','bert']],
['mlm-vs-clm','Masked LM vs Causal LM','마스크드 LM vs 인과 LM','nlp',2,['bert','gpt1','ul2']],
['nlp-tasks','NER · Classification · QA · NLI','NLP 과제 종류','nlp',1,['bert','squad','multinli']],
['seq2seq-c','Sequence-to-Sequence','시퀀스 투 시퀀스','nlp',1,['seq2seq','bahdanau','t5']],
['chunking','Chunking · Text Splitting','청킹 · 텍스트 분할','nlp',2,['rag','lost-in-the-middle']],
['semantic-search','Semantic Search · Vector Database','의미 검색과 벡터 DB','nlp',2,['dpr','faiss','hnsw']],
['system-prompt','System Prompt · Role','시스템 프롬프트와 역할','llmops',1,['instructgpt','ifeval']],
['function-calling','Function Calling · Tool Use','함수 호출과 도구 사용','llmops',1,['toolformer','react']],
['structured-output','Structured Output · JSON Mode','구조화 출력','llmops',2,['ifeval','metagpt']],
['streaming-output','Streaming · Time to First Token','스트리밍과 첫 토큰 지연','llmops',2,['vllm','eagle']],
['batch-inference','Batching · Continuous Batching','배치 추론','llmops',2,['vllm','sglang']],
['token-cost','Token Cost · Pricing','토큰 비용 계산','llmops',1,['gpt3','chinchilla']],
['context-management','Context Management · Memory','문맥 관리와 메모리','llmops',2,['lost-in-the-middle','streaming-llm','generative-agents']],
['guardrails','Guardrails · Safety Filter','가드레일과 안전 필터','llmops',2,['constitutional','red-teaming-lm','gcg']],
['llm-as-judge','LLM as a Judge','LLM 평가자','llmops',2,['chatbot-arena','alpaca-eval']],
['finetune-data','Building Fine-tuning Data','미세조정 데이터 만들기','llmops',2,['self-instruct','flan-collection','unnatural-instructions']],
['local-llm','Local Inference · GGUF · llama.cpp','로컬 실행과 양자화 배포','llmops',2,['llm-int8','awq','bitnet']],
['model-selection','Choosing a Model','모델 고르기','llmops',1,['chinchilla','mmlu-pro','livecodebench']],
['prompt-injection-c','Prompt Injection','프롬프트 주입','llmops',2,['gcg','adversarial-triggers']],
['autoencoder','Autoencoder','오토인코더','genmodel',1,['vae','mae']],
['vae-c','VAE','변분 오토인코더','genmodel',2,['vae','vqvae']],
['gan-c','GAN','생성적 적대 신경망','genmodel',1,['gan','dcgan','improved-gan']],
['latent-space','Latent Space','잠재 공간','genmodel',2,['vae','ldm','stylegan']],
['noise-schedule','Noise Schedule · Sampler','잡음 일정과 샘플러','genmodel',3,['ddpm','ddim','iddpm']],
['conditioning','Conditioning · ControlNet · Adapter','조건 부여','genmodel',2,['cfg','controlnet','ip-adapter']],
['inpainting','Inpainting · Outpainting','인페인팅 · 아웃페인팅','genmodel',2,['ldm','sdedit']],
['upscaling','Upscaling · Super Resolution','업스케일링','genmodel',1,['esrgan','real-esrgan','swinir']],
['mdp','MDP · State · Action · Reward','마르코프 결정 과정','rlc',1,['dqn']],
['policy-value','Policy · Value · Q-Function','정책 · 가치 · Q함수','rlc',1,['dqn','ppo']],
['exploration','Exploration vs Exploitation','탐험과 활용','rlc',1,['dqn','apex']],
['bellman','Bellman Equation','벨만 방정식','rlc',2,['dqn','muzero']],
['mc-vs-td','Monte Carlo vs TD Learning','몬테카를로 vs TD 학습','rlc',2,['dqn','gae']],
['actor-critic','Actor-Critic','액터-크리틱','rlc',2,['a3c','ppo','sac']],
['onpolicy-offpolicy','On-policy vs Off-policy','온폴리시 vs 오프폴리시','rlc',2,['ppo','dqn','td3']],
['reward-design','Reward Design · Reward Hacking','보상 설계와 보상 해킹','rlc',2,['instructgpt','rl-summarization']],
['sim2real','Sim-to-Real Gap','시뮬레이션-실제 격차','rlc',2,['dexterity','rt1']],
['experiment-tracking','Experiment Tracking','실험 추적','mlops',1,['nnunet']],
['model-registry','Model Registry · Versioning','모델 레지스트리','mlops',2,['huggingface']],
['serving-arch','Serving Architecture','서빙 아키텍처','mlops',2,['vllm','tensorflow']],
['batch-vs-realtime','Batch vs Real-time Inference','배치 추론 vs 실시간 추론','mlops',1,['vllm']],
['ab-test','A/B Test · Online Evaluation','A/B 테스트와 온라인 평가','mlops',2,['youtube-dnn','din']],
['drift','Data Drift · Concept Drift','데이터 드리프트','mlops',2,['tent','imagenet-v2']],
['retraining','Retraining · Continual Update','재학습 파이프라인','mlops',2,['ewc','icarl']],
['feature-store','Feature Store','피처 스토어','mlops',3,['wide-deep']],
['cost-optimization','Inference Cost Optimization','추론 비용 최적화','mlops',2,['gptq','vllm','distillation']],
['reproducibility','Reproducibility','재현성','mlops',2,['pythia','olmo']]
];

WIKI.CONCEPT_META = WIKI.CONCEPTS.map(function(r){
  return { slug:r[0], name:r[1], ko:r[2], group:r[3], level:r[4], papers:r[5] };
});
