/* ============================================================
   AI Wiki — 분야(계보) 정의 + 논문 인덱스
   각 논문의 본문은 content/papers/<slug>.js 에 있습니다.
   ============================================================ */
window.WIKI = window.WIKI || {};

WIKI.FIELDS = [
  { id:'foundations', name:'기초 · 학습 알고리즘', en:'Foundations',
    color:'var(--field-foundations)',
    blurb:'신경망을 "학습 가능한 것"으로 만든 알고리즘들. 역전파, 정규화, 옵티마이저처럼 모든 분야가 공유하는 바닥돌.',
    tracks:[
      {id:'learning', name:'학습의 발명'},
      {id:'stabilize', name:'깊게 쌓기 위한 장치'},
      {id:'data',      name:'데이터와 벤치마크'},
      {id:'transfer',  name:'전이 · 도메인 적응'}
    ]},

  { id:'vision', name:'컴퓨터 비전', en:'Vision',
    color:'var(--field-vision)',
    blurb:'"픽셀에서 의미로". CNN이 특징 설계를 대체하고, detection·segmentation으로 확장되고, 결국 Transformer에 흡수되기까지.',
    tracks:[
      {id:'cnn',     name:'CNN 백본 계보'},
      {id:'detect',  name:'객체 탐지'},
      {id:'seg',     name:'분할(Segmentation)'},
      {id:'vit',     name:'Vision Transformer'},
      {id:'selfsup', name:'자기지도 학습'},
      {id:'dense',   name:'포즈 · 깊이 · 흐름'}
    ]},

  { id:'nlp', name:'언어 표현 (Transformer 이전)', en:'Classic NLP',
    color:'var(--field-nlp)',
    blurb:'단어를 벡터로, 문장을 시퀀스로. RNN·LSTM·seq2seq·attention이 Transformer로 가는 길을 깔았다.',
    tracks:[
      {id:'repr', name:'단어 표현'},
      {id:'seq',  name:'시퀀스 모델링'}
    ]},

  { id:'llm', name:'Transformer · 대규모 언어모델', en:'LLM',
    color:'var(--field-llm)',
    blurb:'attention 하나로 아키텍처를 통일한 뒤, 사전학습 → 스케일링 → 정렬(alignment)로 이어진 현대 LLM의 본류.',
    tracks:[
      {id:'core',     name:'아키텍처 원점'},
      {id:'pretrain', name:'사전학습 패러다임'},
      {id:'scale',    name:'스케일링 법칙'},
      {id:'align',    name:'정렬 · 지시 학습'},
      {id:'open',     name:'오픈 웨이트 모델'},
      {id:'context',  name:'긴 문맥'}
    ]},

  { id:'efficiency', name:'효율 · 시스템', en:'Efficiency & Systems',
    color:'var(--field-efficiency)',
    blurb:'같은 모델을 더 싸게, 더 길게, 더 빠르게. 커널·위치인코딩·PEFT·양자화·서빙·상태공간 모델.',
    tracks:[
      {id:'attn',  name:'attention 개조'},
      {id:'peft',  name:'파라미터 효율 미세조정'},
      {id:'quant', name:'양자화 · 압축'},
      {id:'serve', name:'학습 · 서빙 시스템'},
      {id:'ssm',   name:'attention 대안 (SSM)'}
    ]},

  { id:'generative', name:'생성 모델', en:'Generative Models',
    color:'var(--field-generative)',
    blurb:'분포를 배워 새로 만들어 내기. GAN → VAE → Diffusion으로 이어진 이미지 생성의 주류 교체, 그리고 3D.',
    tracks:[
      {id:'gan',       name:'GAN 계보'},
      {id:'vae',       name:'VAE · 이산 잠재'},
      {id:'diffusion', name:'Diffusion 계보'},
      {id:'threeD',    name:'3D · 뉴럴 렌더링'}
    ]},

  { id:'multimodal', name:'멀티모달 · VLM', en:'Multimodal',
    color:'var(--field-multimodal)',
    blurb:'이미지·오디오를 언어와 같은 공간에 올리기. 대조학습으로 시작해 LLM에 눈을 붙이는 방향으로 수렴했다.',
    tracks:[
      {id:'contrastive', name:'대조학습 정렬'},
      {id:'vlm',         name:'Vision-Language 모델'}
    ]},

  { id:'rl', name:'강화학습', en:'Reinforcement Learning',
    color:'var(--field-rl)',
    blurb:'보상으로 배우는 계보. Atari에서 바둑, 그리고 사람 선호(RLHF)를 거쳐 LLM 추론 학습까지 이어진다.',
    tracks:[
      {id:'value',  name:'가치 기반'},
      {id:'policy', name:'정책 경사'},
      {id:'search', name:'탐색 + 학습'},
      {id:'rlhf',   name:'사람 피드백 · LLM RL'},
      {id:'world',  name:'세계 모델'}
    ]},

  { id:'agent', name:'추론 · 도구 · 검색', en:'Reasoning & Agents',
    color:'var(--field-agent)',
    blurb:'모델을 "쓰는 법"이 곧 능력이 된 영역. 사고 사슬로 추론을 끌어내고, 도구를 쥐여 주고, 결국 추론 자체를 학습시키기까지.',
    tracks:[
      {id:'reason',    name:'추론 유도'},
      {id:'tool',      name:'도구 · 에이전트'}
    ]},

  { id:'interp', name:'해석 · 평가', en:'Interpretability & Eval',
    color:'var(--field-interp)',
    blurb:'모델 안에서 무슨 일이 일어나는지, 그리고 잘하는지 어떻게 재는지. 성능 경쟁 뒤편의 인프라. 안전은 별도 분야로 다룬다.',
    tracks:[
      {id:'interp', name:'내부 해석'},
      {id:'eval',   name:'벤치마크'},
      {id:'xai',    name:'설명가능성(XAI)'},
      {id:'trust',  name:'불확실성 · 분포 밖 탐지'}
    ]},

  { id:'speech', name:'음성 · 오디오', en:'Speech & Audio',
    color:'var(--field-speech)',
    blurb:'파형을 이해하고 만들어 내기. 음성 인식이 자기지도로 라벨 갈증을 푼 흐름과, 합성이 보코더 → 종단간 → 코덱 언어모델로 옮겨간 흐름이 나란히 간다.',
    tracks:[
      {id:'asr',   name:'음성 인식'},
      {id:'tts',   name:'음성 합성'},
      {id:'codec', name:'뉴럴 코덱 · 오디오 LM'}
    ]},

  { id:'graph', name:'그래프 신경망', en:'Graph Neural Networks',
    color:'var(--field-graph)',
    blurb:'격자도 시퀀스도 아닌 데이터. 이웃에게 메시지를 보내 자기를 갱신한다는 한 가지 원리가 분자·소셜·추천·지식그래프로 퍼졌다.',
    tracks:[
      {id:'embed',      name:'그래프 임베딩'},
      {id:'conv',       name:'그래프 합성곱'},
      {id:'expressive', name:'표현력 · Transformer'}
    ]},

  { id:'tabular', name:'정형 데이터 · 시계열', en:'Tabular & Time Series',
    color:'var(--field-tabular)',
    blurb:'딥러닝이 이기지 못한 영역. 표와 시계열에서는 아직도 그래디언트 부스팅과 단순한 선형 기저가 강하고, 그 사실 자체가 중요한 정보다.',
    tracks:[
      {id:'gbdt',    name:'그래디언트 부스팅'},
      {id:'deep',    name:'표를 위한 딥러닝'},
      {id:'forecast',name:'시계열 예측'}
    ]},

  { id:'recsys', name:'추천 시스템', en:'Recommender Systems',
    color:'var(--field-recsys)',
    blurb:'가장 오래됐고 가장 돈이 되는 응용. 행렬 분해에서 딥러닝으로, 다시 사용자 행동을 시퀀스로 보는 방향으로 옮겨왔다.',
    tracks:[
      {id:'cf',   name:'협업 필터링'},
      {id:'deep', name:'딥러닝 추천'},
      {id:'seq',  name:'순차 추천'}
    ]},

  { id:'ir', name:'정보검색 · 임베딩', en:'Retrieval & Embeddings',
    color:'var(--field-ir)',
    blurb:'"의미가 비슷한 것을 빨리 찾기". 문장을 벡터로 만드는 쪽과 수십억 벡터에서 근사 최근접을 찾는 쪽이 함께 발전해, 검색 증강(RAG)이라는 오늘날의 표준 구성으로 모였다.',
    tracks:[
      {id:'dense', name:'밀집 검색 · RAG'},
      {id:'embed', name:'문장 임베딩'},
      {id:'late',  name:'후기 상호작용 · 희소'},
      {id:'index', name:'벡터 인덱스'}
    ]},

  { id:'code', name:'코드 AI', en:'Code AI',
    color:'var(--field-code)',
    blurb:'코드는 실행해서 정답을 판정할 수 있는 드문 영역이다. 그 성질이 평가 방식과 강화학습·에이전트 연구를 다른 분야보다 빠르게 밀어붙였다.',
    tracks:[
      {id:'pretrain', name:'코드 사전학습'},
      {id:'bench',    name:'평가'},
      {id:'agent',    name:'소프트웨어 에이전트'}
    ]},

  { id:'video', name:'비디오 · 시공간', en:'Video',
    color:'var(--field-video)',
    blurb:'시간 축이 하나 더 붙는 순간 연산량과 데이터 요구가 폭증한다. 이해 쪽과 생성 쪽 모두 "시간을 어떻게 다룰 것인가"의 답을 찾아왔다.',
    tracks:[
      {id:'understand', name:'비디오 이해'},
      {id:'generate',   name:'비디오 생성'}
    ]},

  { id:'robotics', name:'로보틱스 · 구현 AI', en:'Robotics & Embodied AI',
    color:'var(--field-robotics)',
    blurb:'인터넷 데이터로 배운 능력을 몸을 가진 기계로 옮기기. 언어모델이 계획을 세우고 정책이 몸을 움직이는 구조로 수렴하고 있다.',
    tracks:[
      {id:'imitation', name:'모방학습 정책'},
      {id:'vla',       name:'비전-언어-행동 모델'}
    ]},

  { id:'science', name:'과학을 위한 AI', en:'AI for Science',
    color:'var(--field-science)',
    blurb:'벤치마크가 아니라 실제 자연을 맞히는 분야. 단백질 구조·기상·재료·수학에서 기존 수치해석을 대체하거나 앞지른 사례들.',
    tracks:[
      {id:'bio',  name:'생명 · 단백질'},
      {id:'phys', name:'물리 · 기상'},
      {id:'math', name:'수학 · 재료'}
    ]},

  { id:'data', name:'데이터 중심 AI', en:'Data-Centric AI',
    color:'var(--field-data)',
    blurb:'모델을 바꾸는 대신 데이터를 바꾼다. 무엇을 얼마나 넣느냐가 아키텍처보다 성능을 좌우한다는 것이 드러난 뒤 생긴 연구 계열.',
    tracks:[
      {id:'corpus', name:'대규모 코퍼스'},
      {id:'curate', name:'정제 · 선별'},
      {id:'synth',  name:'합성 데이터'}
    ]},

  { id:'theory', name:'학습 이론 · 일반화', en:'Learning Theory',
    color:'var(--field-theory)',
    blurb:'왜 되는지 모르는 채로 잘 되던 것들에 설명을 붙이려는 시도. 고전 통계학습 이론이 딥러닝 앞에서 깨진 자리에서 시작한다.',
    tracks:[
      {id:'general', name:'일반화의 수수께끼'},
      {id:'optim',   name:'최적화 · 배치 크기'}
    ]},

  { id:'privacy', name:'프라이버시 · 공격 · 안전', en:'Privacy & Security',
    color:'var(--field-privacy)',
    blurb:'모델은 학습 데이터를 기억하고, 사람은 모델을 속인다. 데이터를 지키는 쪽과 모델을 뚫는 쪽이 서로를 밀어 온 계보.',
    tracks:[
      {id:'dp',     name:'차등 프라이버시'},
      {id:'fed',    name:'연합학습'},
      {id:'attack', name:'공격 · 감사'},
      {id:'safety', name:'모델 안전'}
    ]}
];

/* ------------------------------------------------------------
   분야 묶음 — 21개 분야는 서로 다른 기준으로 나뉜다.
   모달리티(무엇을 다루는가) · 응용(어디에 쓰는가) · 횡단(모든 분야를 가로지름).
   한 논문이 여러 곳에 정당하게 속할 수 있으므로, 분야는 배타적 분류가 아니라
   탐색용 서랍으로 본다. 지식의 실제 구조는 WIKI.INDEX 의 계보 그래프에 있다.
   ------------------------------------------------------------ */
WIKI.GROUPS = [
  { id:'base',  name:'기반',
    desc:'모든 분야가 딛고 서는 학습 알고리즘과, 그것이 왜 되는지를 묻는 이론.',
    fields:['foundations','theory'] },
  { id:'modal', name:'모달리티 · 응용',
    desc:'무엇을 다루는가(이미지·언어·음성·영상·그래프)와 어디에 쓰는가(추천·코드·로봇·과학).',
    fields:['vision','nlp','llm','generative','multimodal','speech','video',
            'graph','rl','robotics','recsys','tabular','ir','code','science'] },
  { id:'cross', name:'가로지르는 관심사',
    desc:'특정 모달리티에 속하지 않고 전 분야를 관통하는 문제 — 효율, 데이터, 추론 방식, 해석, 안전.',
    fields:['efficiency','data','agent','interp','privacy'] }
];

/* ------------------------------------------------------------
   논문 인덱스
   [slug, year, 원제, 통칭/한줄, field, track, parents[]]
   parents = 직접적인 지적 선행 논문 (계보 화살표)
   ------------------------------------------------------------ */
WIKI.INDEX = [
// ── foundations ────────────────────────────────────────────
['perceptron',1958,'The Perceptron: A Probabilistic Model for Information Storage','퍼셉트론','foundations','learning',[]],
['backprop',1986,'Learning Representations by Back-Propagating Errors','역전파','foundations','learning',['perceptron']],
['lstm',1997,'Long Short-Term Memory','LSTM','nlp','seq',['backprop']],
['imagenet',2009,'ImageNet: A Large-Scale Hierarchical Image Database','ImageNet','foundations','data',[]],
['dropout',2014,'Dropout: A Simple Way to Prevent Neural Networks from Overfitting','드롭아웃','foundations','stabilize',['alexnet']],
['batchnorm',2015,'Batch Normalization','배치 정규화','foundations','stabilize',['dropout']],
['adam',2015,'Adam: A Method for Stochastic Optimization','Adam 옵티마이저','foundations','learning',['backprop']],
['layernorm',2016,'Layer Normalization','레이어 정규화','foundations','stabilize',['batchnorm']],
['distillation',2015,'Distilling the Knowledge in a Neural Network','지식 증류','foundations','learning',['dropout']],

// ── vision ─────────────────────────────────────────────────
['lenet',1998,'Gradient-Based Learning Applied to Document Recognition','LeNet-5','vision','cnn',['backprop']],
['alexnet',2012,'ImageNet Classification with Deep CNNs','AlexNet','vision','cnn',['lenet','imagenet']],
['vgg',2014,'Very Deep Convolutional Networks (VGG)','VGG','vision','cnn',['alexnet']],
['googlenet',2014,'Going Deeper with Convolutions (GoogLeNet/Inception)','Inception','vision','cnn',['alexnet']],
['resnet',2015,'Deep Residual Learning for Image Recognition','ResNet','vision','cnn',['vgg','googlenet','batchnorm']],
['densenet',2017,'Densely Connected Convolutional Networks','DenseNet','vision','cnn',['resnet']],
['mobilenet',2017,'MobileNets: Efficient CNNs for Mobile Vision','MobileNet','vision','cnn',['resnet']],
['efficientnet',2019,'EfficientNet: Rethinking Model Scaling for CNNs','EfficientNet','vision','cnn',['mobilenet','resnet']],
['convnext',2022,'A ConvNet for the 2020s','ConvNeXt','vision','cnn',['resnet','swin']],
['rcnn',2014,'Rich Feature Hierarchies for Accurate Object Detection (R-CNN)','R-CNN','vision','detect',['alexnet']],
['faster-rcnn',2015,'Faster R-CNN: Towards Real-Time Object Detection with RPN','Faster R-CNN','vision','detect',['rcnn','vgg']],
['yolo',2016,'You Only Look Once: Unified, Real-Time Object Detection','YOLO','vision','detect',['rcnn']],
['ssd',2016,'SSD: Single Shot MultiBox Detector','SSD','vision','detect',['yolo','faster-rcnn']],
['fpn',2017,'Feature Pyramid Networks for Object Detection','FPN','vision','detect',['faster-rcnn']],
['focal-loss',2017,'Focal Loss for Dense Object Detection (RetinaNet)','Focal Loss','vision','detect',['ssd','fpn']],
['detr',2020,'End-to-End Object Detection with Transformers','DETR','vision','detect',['faster-rcnn','transformer']],
['fcn',2015,'Fully Convolutional Networks for Semantic Segmentation','FCN','vision','seg',['vgg']],
['unet',2015,'U-Net: Convolutional Networks for Biomedical Image Segmentation','U-Net','vision','seg',['fcn']],
['mask-rcnn',2017,'Mask R-CNN','Mask R-CNN','vision','seg',['faster-rcnn','fpn']],
['deeplab',2017,'DeepLab: Atrous Convolution for Semantic Segmentation','DeepLab','vision','seg',['fcn']],
['sam',2023,'Segment Anything','SAM','vision','seg',['mask-rcnn','vit','clip']],
['vit',2020,'An Image is Worth 16x16 Words (ViT)','ViT','vision','vit',['transformer','resnet']],
['deit',2021,'Training Data-Efficient Image Transformers (DeiT)','DeiT','vision','vit',['vit','distillation']],
['swin',2021,'Swin Transformer: Hierarchical Vision Transformer','Swin','vision','vit',['vit','fpn']],
['mae',2021,'Masked Autoencoders Are Scalable Vision Learners','MAE','vision','vit',['vit','bert']],
['dino',2021,'Emerging Properties in Self-Supervised Vision Transformers (DINO)','DINO','vision','selfsup',['vit','byol']],
['dinov2',2023,'DINOv2: Learning Robust Visual Features without Supervision','DINOv2','vision','selfsup',['dino','mae']],
['simclr',2020,'A Simple Framework for Contrastive Learning (SimCLR)','SimCLR','vision','selfsup',['resnet']],
['moco',2020,'Momentum Contrast for Unsupervised Visual Representation Learning','MoCo','vision','selfsup',['resnet']],
['byol',2020,'Bootstrap Your Own Latent (BYOL)','BYOL','vision','selfsup',['simclr','moco']],

// ── nlp ────────────────────────────────────────────────────
['nnlm',2003,'A Neural Probabilistic Language Model','신경망 언어모델','nlp','repr',['backprop']],
['word2vec',2013,'Efficient Estimation of Word Representations in Vector Space','word2vec','nlp','repr',['nnlm']],
['glove',2014,'GloVe: Global Vectors for Word Representation','GloVe','nlp','repr',['word2vec']],
['fasttext',2016,'Enriching Word Vectors with Subword Information','fastText','nlp','repr',['word2vec']],
['bpe',2016,'Neural Machine Translation of Rare Words with Subword Units','BPE 토크나이저','nlp','repr',['seq2seq']],
['elmo',2018,'Deep Contextualized Word Representations (ELMo)','ELMo','nlp','repr',['lstm','word2vec']],
['seq2seq',2014,'Sequence to Sequence Learning with Neural Networks','seq2seq','nlp','seq',['lstm']],
['bahdanau',2015,'Neural Machine Translation by Jointly Learning to Align and Translate','Bahdanau attention','nlp','seq',['seq2seq']],

// ── llm ────────────────────────────────────────────────────
['transformer',2017,'Attention Is All You Need','Transformer','llm','core',['bahdanau','layernorm','resnet']],
['gpt1',2018,'Improving Language Understanding by Generative Pre-Training','GPT-1','llm','pretrain',['transformer','elmo']],
['bert',2018,'BERT: Pre-training of Deep Bidirectional Transformers','BERT','llm','pretrain',['transformer','elmo','gpt1']],
['gpt2',2019,'Language Models are Unsupervised Multitask Learners','GPT-2','llm','pretrain',['gpt1']],
['roberta',2019,'RoBERTa: A Robustly Optimized BERT Pretraining Approach','RoBERTa','llm','pretrain',['bert']],
['t5',2019,'Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer','T5','llm','pretrain',['bert','transformer']],
['gpt3',2020,'Language Models are Few-Shot Learners','GPT-3','llm','pretrain',['gpt2','scaling-laws']],
['scaling-laws',2020,'Scaling Laws for Neural Language Models','스케일링 법칙','llm','scale',['gpt2']],
['chinchilla',2022,'Training Compute-Optimal Large Language Models','Chinchilla','llm','scale',['scaling-laws','gpt3']],
['palm',2022,'PaLM: Scaling Language Modeling with Pathways','PaLM','llm','scale',['gpt3']],
['emergent',2022,'Emergent Abilities of Large Language Models','창발 능력','llm','scale',['gpt3','palm']],
['moe-shazeer',2017,'Outrageously Large Neural Networks: Sparsely-Gated MoE','Sparse MoE','llm','scale',['lstm']],
['switch',2021,'Switch Transformers: Scaling to Trillion Parameter Models','Switch Transformer','llm','scale',['moe-shazeer','t5']],
['instructgpt',2022,'Training Language Models to Follow Instructions with Human Feedback','InstructGPT','llm','align',['gpt3','summarize-hf','ppo']],
['flan',2022,'Finetuned Language Models Are Zero-Shot Learners (FLAN)','instruction tuning','llm','align',['t5','gpt3']],
['dpo',2023,'Direct Preference Optimization','DPO','llm','align',['instructgpt']],
['gpt4',2023,'GPT-4 Technical Report','GPT-4','llm','pretrain',['gpt3','instructgpt']],
['llama',2023,'LLaMA: Open and Efficient Foundation Language Models','LLaMA','llm','open',['chinchilla','gpt3','rope']],
['llama2',2023,'Llama 2: Open Foundation and Fine-Tuned Chat Models','Llama 2','llm','open',['llama','instructgpt','gqa']],
['mistral',2023,'Mistral 7B','Mistral 7B','llm','open',['llama','gqa']],
['mixtral',2024,'Mixtral of Experts','Mixtral 8x7B','llm','open',['mistral','switch']],
['deepseek-v3',2024,'DeepSeek-V3 Technical Report','DeepSeek-V3','llm','open',['mixtral','llama2']],

// ── efficiency ─────────────────────────────────────────────
['mqa',2019,'Fast Transformer Decoding: One Write-Head is All You Need','MQA','efficiency','attn',['transformer']],
['sparse-attn',2020,'Longformer / Big Bird: Sparse Attention for Long Documents','희소 attention','efficiency','attn',['transformer']],
['rope',2021,'RoFormer: Enhanced Transformer with Rotary Position Embedding','RoPE','efficiency','attn',['transformer']],
['alibi',2021,'Train Short, Test Long: Attention with Linear Biases (ALiBi)','ALiBi','efficiency','attn',['transformer']],
['flashattention',2022,'FlashAttention: Fast and Memory-Efficient Exact Attention','FlashAttention','efficiency','attn',['transformer']],
['gqa',2023,'GQA: Training Generalized Multi-Query Transformer Models','GQA','efficiency','attn',['mqa','flashattention']],
['adapter',2019,'Parameter-Efficient Transfer Learning for NLP (Adapters)','Adapter','efficiency','peft',['bert']],
['prefix-tuning',2021,'Prefix-Tuning: Optimizing Continuous Prompts for Generation','Prefix Tuning','efficiency','peft',['adapter','gpt2']],
['lora',2021,'LoRA: Low-Rank Adaptation of Large Language Models','LoRA','efficiency','peft',['adapter','prefix-tuning']],
['qlora',2023,'QLoRA: Efficient Finetuning of Quantized LLMs','QLoRA','efficiency','peft',['lora','llm-int8']],
['llm-int8',2022,'LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale','LLM.int8()','efficiency','quant',['gpt3']],
['gptq',2022,'GPTQ: Accurate Post-Training Quantization for Generative Transformers','GPTQ','efficiency','quant',['llm-int8']],
['awq',2023,'AWQ: Activation-aware Weight Quantization','AWQ','efficiency','quant',['gptq']],
['zero',2019,'ZeRO: Memory Optimizations Toward Training Trillion Parameter Models','ZeRO / DeepSpeed','efficiency','serve',['transformer']],
['megatron',2019,'Megatron-LM: Training Multi-Billion Parameter Models with Model Parallelism','Megatron-LM','efficiency','serve',['transformer']],
['vllm',2023,'Efficient Memory Management for LLM Serving with PagedAttention (vLLM)','vLLM / PagedAttention','efficiency','serve',['flashattention','gpt3']],
['speculative',2023,'Fast Inference from Transformers via Speculative Decoding','Speculative Decoding','efficiency','serve',['gpt3']],
['s4',2021,'Efficiently Modeling Long Sequences with Structured State Spaces (S4)','S4','efficiency','ssm',['lstm','transformer']],
['mamba',2023,'Mamba: Linear-Time Sequence Modeling with Selective State Spaces','Mamba','efficiency','ssm',['s4','flashattention']],
['rwkv',2023,'RWKV: Reinventing RNNs for the Transformer Era','RWKV','efficiency','ssm',['lstm','transformer']],

// ── generative ─────────────────────────────────────────────
['vae',2013,'Auto-Encoding Variational Bayes (VAE)','VAE','generative','vae',['backprop']],
['gan',2014,'Generative Adversarial Networks','GAN','generative','gan',['backprop']],
['dcgan',2015,'Unsupervised Representation Learning with Deep Convolutional GANs','DCGAN','generative','gan',['gan','alexnet']],
['pix2pix',2016,'Image-to-Image Translation with Conditional Adversarial Networks','pix2pix','generative','gan',['dcgan','unet']],
['wgan',2017,'Wasserstein GAN','WGAN','generative','gan',['gan']],
['cyclegan',2017,'Unpaired Image-to-Image Translation (CycleGAN)','CycleGAN','generative','gan',['pix2pix']],
['stylegan',2019,'A Style-Based Generator Architecture for GANs (StyleGAN)','StyleGAN','generative','gan',['dcgan','wgan']],
['vqvae',2017,'Neural Discrete Representation Learning (VQ-VAE)','VQ-VAE','generative','vae',['vae']],
['vqgan',2021,'Taming Transformers for High-Resolution Image Synthesis (VQGAN)','VQGAN','generative','vae',['vqvae','gan','transformer']],
['dalle',2021,'Zero-Shot Text-to-Image Generation (DALL·E)','DALL·E','generative','vae',['vqvae','gpt3']],
['ddpm',2020,'Denoising Diffusion Probabilistic Models','DDPM','generative','diffusion',['diffusion-original','vae','unet']],
['score-sde',2021,'Score-Based Generative Modeling through SDEs','Score SDE','generative','diffusion',['ddpm']],
['ddim',2021,'Denoising Diffusion Implicit Models','DDIM','generative','diffusion',['ddpm']],
['cfg',2022,'Classifier-Free Diffusion Guidance','Classifier-Free Guidance','generative','diffusion',['ddpm']],
['ldm',2022,'High-Resolution Image Synthesis with Latent Diffusion Models','Stable Diffusion (LDM)','generative','diffusion',['ddpm','vqgan','cfg','clip']],
['dit',2023,'Scalable Diffusion Models with Transformers (DiT)','DiT','generative','diffusion',['ldm','vit']],
['flow-matching',2023,'Flow Matching for Generative Modeling','Flow Matching','generative','diffusion',['score-sde']],
['consistency',2023,'Consistency Models','Consistency Models','generative','diffusion',['ddim','score-sde']],
['nerf',2020,'NeRF: Representing Scenes as Neural Radiance Fields','NeRF','generative','threeD',['backprop']],
['3dgs',2023,'3D Gaussian Splatting for Real-Time Radiance Field Rendering','3D Gaussian Splatting','generative','threeD',['nerf']],

// ── multimodal ─────────────────────────────────────────────
['clip',2021,'Learning Transferable Visual Models From Natural Language Supervision','CLIP','multimodal','contrastive',['vit','transformer','simclr']],
['align',2021,'Scaling Up Visual and Vision-Language Representation Learning (ALIGN)','ALIGN','multimodal','contrastive',['clip']],
['siglip',2023,'Sigmoid Loss for Language Image Pre-Training (SigLIP)','SigLIP','multimodal','contrastive',['clip']],
['flamingo',2022,'Flamingo: a Visual Language Model for Few-Shot Learning','Flamingo','multimodal','vlm',['clip','gpt3']],
['blip',2022,'BLIP: Bootstrapping Language-Image Pre-training','BLIP','multimodal','vlm',['clip']],
['blip2',2023,'BLIP-2: Bootstrapping Vision-Language Pre-training with Frozen Encoders','BLIP-2','multimodal','vlm',['blip','flamingo']],
['llava',2023,'Visual Instruction Tuning (LLaVA)','LLaVA','multimodal','vlm',['clip','instructgpt','llama']],
['qwen-vl',2023,'Qwen-VL: A Versatile Vision-Language Model','Qwen-VL','multimodal','vlm',['blip2','llava']],
['wav2vec2',2020,'wav2vec 2.0: Self-Supervised Learning of Speech Representations','wav2vec 2.0','speech','asr',['transformer','bert']],
['whisper',2022,'Robust Speech Recognition via Large-Scale Weak Supervision (Whisper)','Whisper','speech','asr',['transformer','wav2vec2']],

// ── rl ─────────────────────────────────────────────────────
['dqn',2015,'Human-Level Control through Deep Reinforcement Learning (DQN)','DQN','rl','value',['backprop','alexnet']],
['ddpg',2016,'Continuous Control with Deep Reinforcement Learning (DDPG)','DDPG','rl','policy',['dqn']],
['a3c',2016,'Asynchronous Methods for Deep Reinforcement Learning (A3C)','A3C','rl','policy',['dqn']],
['trpo',2015,'Trust Region Policy Optimization','TRPO','rl','policy',['backprop']],
['ppo',2017,'Proximal Policy Optimization Algorithms','PPO','rl','policy',['trpo','a3c']],
['sac',2018,'Soft Actor-Critic','SAC','rl','policy',['ddpg']],
['alphago',2016,'Mastering the Game of Go with Deep Neural Networks and Tree Search','AlphaGo','rl','search',['dqn','resnet']],
['alphazero',2017,'Mastering Chess and Shogi by Self-Play (AlphaZero)','AlphaZero','rl','search',['alphago']],
['muzero',2020,'Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model','MuZero','rl','search',['alphazero']],
['rlhf-prefs',2017,'Deep Reinforcement Learning from Human Preferences','RLHF 원형','rl','rlhf',['trpo','a3c']],
['summarize-hf',2020,'Learning to Summarize with Human Feedback','요약 RLHF','rl','rlhf',['rlhf-prefs','gpt3','ppo']],
['grpo',2024,'DeepSeekMath: GRPO and Reasoning-Oriented RL','GRPO','rl','rlhf',['ppo','instructgpt']],

// ── agent ──────────────────────────────────────────────────
['cot',2022,'Chain-of-Thought Prompting Elicits Reasoning in LLMs','Chain-of-Thought','agent','reason',['gpt3','palm']],
['self-consistency',2022,'Self-Consistency Improves Chain of Thought Reasoning','Self-Consistency','agent','reason',['cot']],
['tot',2023,'Tree of Thoughts: Deliberate Problem Solving with LLMs','Tree of Thoughts','agent','reason',['cot','alphazero']],
['deepseek-r1',2025,'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via RL','DeepSeek-R1','agent','reason',['cot','grpo','deepseek-v3']],
['react',2022,'ReAct: Synergizing Reasoning and Acting in Language Models','ReAct','agent','tool',['cot']],
['toolformer',2023,'Toolformer: Language Models Can Teach Themselves to Use Tools','Toolformer','agent','tool',['gpt3','react']],
['dpr',2020,'Dense Passage Retrieval for Open-Domain QA','DPR','ir','dense',['bert']],
['realm',2020,'REALM: Retrieval-Augmented Language Model Pre-Training','REALM','ir','dense',['bert','dpr']],
['rag',2020,'Retrieval-Augmented Generation for Knowledge-Intensive NLP','RAG','ir','dense',['dpr','bert']],

// ── interp ─────────────────────────────────────────────────
['lottery',2019,'The Lottery Ticket Hypothesis','로또 티켓 가설','interp','interp',['dropout']],
['induction-heads',2022,'In-context Learning and Induction Heads','Induction Heads','interp','interp',['transformer','gpt3']],
['grokking',2022,'Grokking: Generalization Beyond Overfitting','Grokking','interp','interp',['transformer']],
['sae',2023,'Towards Monosemanticity: Decomposing Language Models with Dictionary Learning','Sparse Autoencoder','interp','interp',['induction-heads']],
['mmlu',2021,'Measuring Massive Multitask Language Understanding (MMLU)','MMLU','interp','eval',['gpt3']],
['gsm8k',2021,'Training Verifiers to Solve Math Word Problems (GSM8K)','GSM8K','interp','eval',['gpt3']],
['humaneval',2021,'Evaluating Large Language Models Trained on Code (Codex/HumanEval)','HumanEval','interp','eval',['gpt3']],
['bigbench',2022,'Beyond the Imitation Game (BIG-bench)','BIG-bench','interp','eval',['gpt3','mmlu']],
['constitutional',2022,'Constitutional AI: Harmlessness from AI Feedback','Constitutional AI','privacy','safety',['instructgpt']],
['chatbot-arena',2024,'Chatbot Arena: An Open Platform for Evaluating LLMs by Human Preference','Chatbot Arena','interp','eval',['mmlu','instructgpt']],
// ── speech ─────────────────────────────────────────────────
['wavenet',2016,'WaveNet: A Generative Model for Raw Audio','WaveNet','speech','tts',['backprop']],
['tacotron2',2018,'Natural TTS Synthesis by Conditioning WaveNet on Mel Spectrogram Predictions','Tacotron 2','speech','tts',['wavenet','seq2seq','bahdanau']],
['fastspeech',2019,'FastSpeech: Fast, Robust and Controllable Text to Speech','FastSpeech','speech','tts',['tacotron2','transformer']],
['hifi-gan',2020,'HiFi-GAN: Generative Adversarial Networks for Efficient and High Fidelity Speech Synthesis','HiFi-GAN','speech','tts',['wavenet','gan']],
['hubert',2021,'HuBERT: Self-Supervised Speech Representation Learning by Masked Prediction','HuBERT','speech','asr',['wav2vec2','bert']],
['vits',2021,'Conditional VAE with Adversarial Learning for End-to-End Text-to-Speech (VITS)','VITS','speech','tts',['fastspeech','vae','hifi-gan']],
['soundstream',2021,'SoundStream: An End-to-End Neural Audio Codec','SoundStream','speech','codec',['wavenet','vqvae']],
['encodec',2022,'High Fidelity Neural Audio Compression (EnCodec)','EnCodec','speech','codec',['soundstream','vqvae']],
['audiolm',2022,'AudioLM: a Language Modeling Approach to Audio Generation','AudioLM','speech','codec',['encodec','hubert','gpt2']],
['vall-e',2023,'Neural Codec Language Models are Zero-Shot Text to Speech Synthesizers (VALL-E)','VALL-E','speech','codec',['encodec','audiolm','gpt3']],

// ── graph ──────────────────────────────────────────────────
['deepwalk',2014,'DeepWalk: Online Learning of Social Representations','DeepWalk','graph','embed',['word2vec']],
['node2vec',2016,'node2vec: Scalable Feature Learning for Networks','node2vec','graph','embed',['deepwalk','word2vec']],
['gcn',2017,'Semi-Supervised Classification with Graph Convolutional Networks','GCN','graph','conv',['backprop','lenet']],
['graphsage',2017,'Inductive Representation Learning on Large Graphs (GraphSAGE)','GraphSAGE','graph','conv',['gcn']],
['mpnn',2017,'Neural Message Passing for Quantum Chemistry','MPNN','graph','conv',['gcn']],
['gat',2018,'Graph Attention Networks','GAT','graph','conv',['gcn','bahdanau']],
['gin',2019,'How Powerful are Graph Neural Networks? (GIN)','GIN','graph','expressive',['gcn','graphsage']],
['graphormer',2021,'Do Transformers Really Perform Bad for Graph Representation? (Graphormer)','Graphormer','graph','expressive',['gat','transformer']],

// ── recsys ─────────────────────────────────────────────────
['mf',2009,'Matrix Factorization Techniques for Recommender Systems','행렬 분해','recsys','cf',[]],
['youtube-dnn',2016,'Deep Neural Networks for YouTube Recommendations','YouTube DNN','recsys','deep',['mf','word2vec']],
['wide-deep',2016,'Wide & Deep Learning for Recommender Systems','Wide & Deep','recsys','deep',['mf']],
['ncf',2017,'Neural Collaborative Filtering','NCF','recsys','deep',['mf']],
['deepfm',2017,'DeepFM: A Factorization-Machine based Neural Network for CTR Prediction','DeepFM','recsys','deep',['wide-deep']],
['din',2018,'Deep Interest Network for Click-Through Rate Prediction','DIN','recsys','deep',['deepfm','bahdanau']],
['sasrec',2018,'Self-Attentive Sequential Recommendation','SASRec','recsys','seq',['transformer','mf']],
['bert4rec',2019,'BERT4Rec: Sequential Recommendation with Bidirectional Transformer','BERT4Rec','recsys','seq',['sasrec','bert']],
['two-tower',2019,'Sampling-Bias-Corrected Neural Modeling for Large Corpus Item Recommendations','투 타워','recsys','deep',['youtube-dnn','ncf']],

// ── ir ─────────────────────────────────────────────────────
['hnsw',2016,'Efficient and Robust Approximate Nearest Neighbor Search Using HNSW Graphs','HNSW','ir','index',[]],
['faiss',2017,'Billion-Scale Similarity Search with GPUs (FAISS)','FAISS','ir','index',['hnsw']],
['sentence-bert',2019,'Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks','Sentence-BERT','ir','embed',['bert']],
['colbert',2020,'ColBERT: Efficient and Effective Passage Search via Late Interaction','ColBERT','ir','late',['bert','dpr']],
['simcse',2021,'SimCSE: Simple Contrastive Learning of Sentence Embeddings','SimCSE','ir','embed',['sentence-bert','simclr']],
['splade',2021,'SPLADE: Sparse Lexical and Expansion Model for Information Retrieval','SPLADE','ir','late',['bert','colbert']],
['e5',2022,'Text Embeddings by Weakly-Supervised Contrastive Pre-training (E5)','E5','ir','embed',['simcse','sentence-bert']],
['bge',2023,'C-Pack: Packed Resources For General Chinese Embeddings (BGE)','BGE','ir','embed',['e5']],

// ── code ───────────────────────────────────────────────────
['codebert',2020,'CodeBERT: A Pre-Trained Model for Programming and Natural Languages','CodeBERT','code','pretrain',['bert','roberta']],
['codet5',2021,'CodeT5: Identifier-aware Unified Pre-trained Encoder-Decoder Models for Code','CodeT5','code','pretrain',['t5','codebert']],
['alphacode',2022,'Competition-Level Code Generation with AlphaCode','AlphaCode','code','pretrain',['transformer','humaneval']],
['starcoder',2023,'StarCoder: may the source be with you!','StarCoder','code','pretrain',['codet5','llama']],
['codellama',2023,'Code Llama: Open Foundation Models for Code','Code Llama','code','pretrain',['llama2','starcoder']],
['swe-bench',2023,'SWE-bench: Can Language Models Resolve Real-World GitHub Issues?','SWE-bench','code','bench',['humaneval','gpt4']],
['deepseek-coder',2024,'DeepSeek-Coder: When the Large Language Model Meets Programming','DeepSeek-Coder','code','pretrain',['codellama','deepseek-v3']],
['swe-agent',2024,'SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering','SWE-agent','code','agent',['swe-bench','react']],

// ── video ──────────────────────────────────────────────────
['two-stream',2014,'Two-Stream Convolutional Networks for Action Recognition in Videos','Two-Stream','video','understand',['alexnet']],
['i3d',2017,'Quo Vadis, Action Recognition? A New Model and the Kinetics Dataset (I3D)','I3D','video','understand',['two-stream','googlenet']],
['slowfast',2019,'SlowFast Networks for Video Recognition','SlowFast','video','understand',['i3d','resnet']],
['timesformer',2021,'Is Space-Time Attention All You Need for Video Understanding? (TimeSformer)','TimeSformer','video','understand',['vit','i3d']],
['video-diffusion',2022,'Video Diffusion Models','Video Diffusion','video','generate',['ddpm','unet']],
['videomae',2022,'VideoMAE: Masked Autoencoders are Data-Efficient Learners for Video','VideoMAE','video','understand',['mae','timesformer']],
['make-a-video',2022,'Make-A-Video: Text-to-Video Generation without Text-Video Data','Make-A-Video','video','generate',['video-diffusion','dalle']],
['videoldm',2023,'Align your Latents: High-Resolution Video Synthesis with Latent Diffusion Models','Video LDM','video','generate',['ldm','video-diffusion']],
['svd',2023,'Stable Video Diffusion: Scaling Latent Video Diffusion Models to Large Datasets','Stable Video Diffusion','video','generate',['videoldm','ldm']],

// ── robotics ───────────────────────────────────────────────
['gato',2022,'A Generalist Agent (Gato)','Gato','robotics','vla',['transformer','dqn']],
['saycan',2022,'Do As I Can, Not As I Say: Grounding Language in Robotic Affordances (SayCan)','SayCan','robotics','vla',['palm','cot']],
['rt1',2022,'RT-1: Robotics Transformer for Real-World Control at Scale','RT-1','robotics','vla',['gato','efficientnet']],
['act',2023,'Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware (ACT / ALOHA)','ACT · ALOHA','robotics','imitation',['transformer','vae']],
['diffusion-policy',2023,'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion','Diffusion Policy','robotics','imitation',['ddpm','act']],
['rt2',2023,'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control','RT-2','robotics','vla',['rt1','clip','palm']],
['openvla',2024,'OpenVLA: An Open-Source Vision-Language-Action Model','OpenVLA','robotics','vla',['rt2','llava']],
['pi0',2024,'π0: A Vision-Language-Action Flow Model for General Robot Control','π0','robotics','vla',['openvla','diffusion-policy','flow-matching']],

// ── science ────────────────────────────────────────────────
['fno',2021,'Fourier Neural Operator for Parametric Partial Differential Equations','FNO','science','phys',['backprop']],
['alphafold',2021,'Highly Accurate Protein Structure Prediction with AlphaFold','AlphaFold 2','science','bio',['transformer','resnet']],
['esmfold',2023,'Evolutionary-Scale Prediction of Atomic-Level Protein Structure with a Language Model','ESMFold','science','bio',['alphafold','bert']],
['graphcast',2023,'GraphCast: Learning Skillful Medium-Range Global Weather Forecasting','GraphCast','science','phys',['gcn','mpnn']],
['pangu-weather',2023,'Accurate Medium-Range Global Weather Forecasting with 3D Neural Networks','Pangu-Weather','science','phys',['vit','fno']],
['gnome',2023,'Scaling Deep Learning for Materials Discovery (GNoME)','GNoME','science','math',['gcn','mpnn']],
['alphageometry',2024,'Solving Olympiad Geometry without Human Demonstrations','AlphaGeometry','science','math',['transformer','alphazero']],
['alphafold3',2024,'Accurate Structure Prediction of Biomolecular Interactions with AlphaFold 3','AlphaFold 3','science','bio',['alphafold','ddpm']],

// ── data ───────────────────────────────────────────────────
['the-pile',2020,'The Pile: An 800GB Dataset of Diverse Text for Language Modeling','The Pile','data','corpus',['gpt3']],
['dedup',2022,'Deduplicating Training Data Makes Language Models Better','중복 제거','data','curate',['the-pile','gpt2']],
['laion5b',2022,'LAION-5B: An Open Large-Scale Dataset for Training Next Generation Image-Text Models','LAION-5B','data','corpus',['clip']],
['self-instruct',2022,'Self-Instruct: Aligning Language Models with Self-Generated Instructions','Self-Instruct','data','synth',['gpt3','flan']],
['refinedweb',2023,'The RefinedWeb Dataset for Falcon LLM','RefinedWeb','data','curate',['the-pile','chinchilla']],
['datacomp',2023,'DataComp: In Search of the Next Generation of Multimodal Datasets','DataComp','data','curate',['laion5b','clip']],
['phi-textbooks',2023,'Textbooks Are All You Need (phi-1)','교과서 데이터','data','synth',['self-instruct','chinchilla']],
['data-constrained',2023,'Scaling Data-Constrained Language Models','데이터 제약 스케일링','data','curate',['chinchilla','scaling-laws']],

// ── theory ─────────────────────────────────────────────────
['rethinking-generalization',2017,'Understanding Deep Learning Requires Rethinking Generalization','일반화 재고','theory','general',['dropout','batchnorm']],
['large-batch',2017,'On Large-Batch Training for Deep Learning: Generalization Gap and Sharp Minima','큰 배치의 함정','theory','optim',['adam','batchnorm']],
['lr-scaling',2017,'Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour','선형 스케일링 규칙','theory','optim',['large-batch','resnet']],
['ntk',2018,'Neural Tangent Kernel: Convergence and Generalization in Neural Networks','신경 접선 커널','theory','general',['backprop']],
['empirical-batch',2018,'An Empirical Model of Large-Batch Training','임계 배치 크기','theory','optim',['large-batch','adam']],
['double-descent',2019,'Deep Double Descent: Where Bigger Models and More Data Hurt','이중 하강','theory','general',['rethinking-generalization','lottery']],

// ── privacy ────────────────────────────────────────────────
['dp-sgd',2016,'Deep Learning with Differential Privacy (DP-SGD)','DP-SGD','privacy','dp',['backprop']],
['fedavg',2017,'Communication-Efficient Learning of Deep Networks from Decentralized Data (FedAvg)','FedAvg','privacy','fed',['backprop']],
['membership-inference',2017,'Membership Inference Attacks Against Machine Learning Models','멤버십 추론 공격','privacy','attack',['dp-sgd']],
['extracting-training-data',2021,'Extracting Training Data from Large Language Models','학습 데이터 추출','privacy','attack',['gpt2','membership-inference']],
['red-teaming',2022,'Red Teaming Language Models to Reduce Harms','레드팀','privacy','safety',['instructgpt']],
['watermark',2023,'A Watermark for Large Language Models','LLM 워터마크','privacy','safety',['gpt3']],
['universal-jailbreak',2023,'Universal and Transferable Adversarial Attacks on Aligned Language Models','범용 탈옥 공격','privacy','attack',['llama2','gpt4']],
['sleeper-agents',2024,'Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training','슬리퍼 에이전트','privacy','safety',['constitutional','instructgpt']],

// ── llm / 긴 문맥 ──────────────────────────────────────────
['position-interpolation',2023,'Extending Context Window of Large Language Models via Positional Interpolation','위치 보간','llm','context',['rope','llama']],
['lost-in-the-middle',2023,'Lost in the Middle: How Language Models Use Long Contexts','중간을 잃다','llm','context',['gpt4','rag']],
['yarn',2023,'YaRN: Efficient Context Window Extension of Large Language Models','YaRN','llm','context',['rope','position-interpolation']],
['ring-attention',2023,'Ring Attention with Blockwise Transformers for Near-Infinite Context','Ring Attention','llm','context',['flashattention','transformer']],

// ── agent / 도구 추가 ──────────────────────────────────────
['reflexion',2023,'Reflexion: Language Agents with Verbal Reinforcement Learning','Reflexion','agent','tool',['react','cot']],
['voyager',2023,'Voyager: An Open-Ended Embodied Agent with Large Language Models','Voyager','agent','tool',['react','gpt4']],
['generative-agents',2023,'Generative Agents: Interactive Simulacra of Human Behavior','생성 에이전트','agent','tool',['react','gpt4']],

// ════════ 2차 확장 ════════
// ── vision ─────────────────────────────────────────────────
['spatial-transformer',2015,'Spatial Transformer Networks','Spatial Transformer','vision','cnn',['alexnet','backprop']],
['openpose',2017,'Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields','OpenPose','vision','dense',['fcn','vgg']],
['senet',2018,'Squeeze-and-Excitation Networks','SENet','vision','cnn',['resnet','googlenet']],
['mixup',2018,'mixup: Beyond Empirical Risk Minimization','mixup','vision','cnn',['resnet','dropout']],
['raft',2020,'RAFT: Recurrent All-Pairs Field Transforms for Optical Flow','RAFT','vision','dense',['fcn','lstm']],
['depth-anything',2024,'Depth Anything: Unleashing the Power of Large-Scale Unlabeled Data','Depth Anything','vision','dense',['dinov2','sam']],

// ── nlp / llm ──────────────────────────────────────────────
['sentencepiece',2018,'SentencePiece: A Simple and Language Independent Subword Tokenizer','SentencePiece','nlp','repr',['bpe']],
['bart',2019,'BART: Denoising Sequence-to-Sequence Pre-training','BART','llm','pretrain',['bert','t5','transformer']],
['electra',2020,'ELECTRA: Pre-training Text Encoders as Discriminators Rather Than Generators','ELECTRA','llm','pretrain',['bert','gan']],
['qwen2',2024,'Qwen2 Technical Report','Qwen2','llm','open',['llama2','gqa','rope']],
['olmo',2024,'OLMo: Accelerating the Science of Language Models','OLMo','llm','open',['llama','the-pile']],

// ── efficiency ─────────────────────────────────────────────
['flashattention2',2023,'FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning','FlashAttention-2','efficiency','attn',['flashattention']],
['medusa',2024,'Medusa: Simple LLM Inference Acceleration with Multiple Decoding Heads','Medusa','efficiency','serve',['speculative','vllm']],
['sglang',2024,'SGLang: Efficient Execution of Structured Language Model Programs','SGLang','efficiency','serve',['vllm','flashattention']],
['mamba2',2024,'Transformers are SSMs: Generalized Models and Efficient Algorithms (Mamba-2)','Mamba-2','efficiency','ssm',['mamba','flashattention']],

// ── generative ─────────────────────────────────────────────
['imagen',2022,'Photorealistic Text-to-Image Diffusion Models with Deep Language Understanding','Imagen','generative','diffusion',['ddpm','cfg','t5']],
['dreambooth',2023,'DreamBooth: Fine Tuning Text-to-Image Diffusion Models for Subject-Driven Generation','DreamBooth','generative','diffusion',['ldm','imagen']],
['controlnet',2023,'Adding Conditional Control to Text-to-Image Diffusion Models (ControlNet)','ControlNet','generative','diffusion',['ldm','cfg']],
['sdxl',2023,'SDXL: Improving Latent Diffusion Models for High-Resolution Image Synthesis','SDXL','generative','diffusion',['ldm','cfg']],

// ── multimodal ─────────────────────────────────────────────
['pali',2022,'PaLI: A Jointly-Scaled Multilingual Language-Image Model','PaLI','multimodal','vlm',['vit','t5','clip']],
['chameleon',2024,'Chameleon: Mixed-Modal Early-Fusion Foundation Models','Chameleon','multimodal','vlm',['vqgan','llama2']],
['internvl',2024,'InternVL: Scaling up Vision Foundation Models and Aligning for Generic Visual-Linguistic Tasks','InternVL','multimodal','vlm',['clip','llava','qwen-vl']],

// ── rl ─────────────────────────────────────────────────────
['world-models',2018,'World Models','World Models','rl','world',['vae','lstm']],
['rainbow',2018,'Rainbow: Combining Improvements in Deep Reinforcement Learning','Rainbow','rl','value',['dqn']],
['alphastar',2019,'Grandmaster Level in StarCraft II using Multi-Agent Reinforcement Learning','AlphaStar','rl','search',['alphazero','lstm','ppo']],
['dreamer',2020,'Dream to Control: Learning Behaviors by Latent Imagination (Dreamer)','Dreamer','rl','world',['world-models','muzero']],

// ── agent ──────────────────────────────────────────────────
['pal',2022,'PAL: Program-aided Language Models','PAL','agent','reason',['cot','humaneval']],
['least-to-most',2022,'Least-to-Most Prompting Enables Complex Reasoning in Large Language Models','Least-to-Most','agent','reason',['cot']],
['self-refine',2023,'Self-Refine: Iterative Refinement with Self-Feedback','Self-Refine','agent','reason',['cot','reflexion']],

// ── interp ─────────────────────────────────────────────────
['lime',2016,'Why Should I Trust You? Explaining the Predictions of Any Classifier (LIME)','LIME','interp','xai',['backprop']],
['grad-cam',2017,'Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization','Grad-CAM','interp','xai',['vgg','resnet']],
['shap',2017,'A Unified Approach to Interpreting Model Predictions (SHAP)','SHAP','interp','xai',['lime']],
['attention-not-explanation',2019,'Attention is not Explanation','attention은 설명이 아니다','interp','xai',['bahdanau','transformer']],
['helm',2022,'Holistic Evaluation of Language Models (HELM)','HELM','interp','eval',['mmlu','bigbench']],

// ── speech · graph · ir ────────────────────────────────────
['conformer',2020,'Conformer: Convolution-augmented Transformer for Speech Recognition','Conformer','speech','asr',['transformer','resnet']],
['pinsage',2018,'Graph Convolutional Neural Networks for Web-Scale Recommender Systems (PinSage)','PinSage','graph','conv',['graphsage','mf']],
['bm25',1994,'Okapi at TREC-3 (BM25)','BM25','ir','late',[]],
['monobert',2019,'Passage Re-ranking with BERT','monoBERT','ir','late',['bert','bm25']],

// ── video · robotics · data · theory · privacy ─────────────
['cogvideox',2024,'CogVideoX: Text-to-Video Diffusion Models with An Expert Transformer','CogVideoX','video','generate',['dit','videoldm']],
['open-x',2023,'Open X-Embodiment: Robotic Learning Datasets and RT-X Models','Open X-Embodiment','robotics','vla',['rt1','rt2']],
['mobile-aloha',2024,'Mobile ALOHA: Learning Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation','Mobile ALOHA','robotics','imitation',['act','diffusion-policy']],
['dolma',2024,'Dolma: an Open Corpus of Three Trillion Tokens for Language Model Pretraining','Dolma','data','corpus',['the-pile','refinedweb']],
['fineweb',2024,'The FineWeb Datasets: Decanting the Web for the Finest Text Data at Scale','FineWeb','data','curate',['refinedweb','dedup']],
['information-bottleneck',2017,'Opening the Black Box of Deep Neural Networks via Information','정보 병목','theory','general',['backprop','rethinking-generalization']],
['sam-optimizer',2021,'Sharpness-Aware Minimization for Efficiently Improving Generalization','SAM 옵티마이저','theory','optim',['large-batch','adam']],
['machine-unlearning',2021,'Machine Unlearning','기계 망각','privacy','dp',['dp-sgd','membership-inference']],

// ════════ 3차 확장 — 원문 참고문헌에서 캐낸 빈 자리 ════════
// (tools/mine_refs.py 로 250편의 참고문헌을 훑어, 우리 위키가 공통으로
//  참조하는데 없던 논문을 참조 빈도 순으로 추린 것)
['adamw',2017,'Decoupled Weight Decay Regularization (AdamW)','AdamW','foundations','learning',['adam']],
['gelu',2016,'Gaussian Error Linear Units (GELUs)','GELU','foundations','stabilize',['backprop','dropout']],
['graves-rnn',2013,'Generating Sequences With Recurrent Neural Networks','Graves RNN','nlp','seq',['lstm']],
['gnmt',2016,"Google's Neural Machine Translation System",'GNMT','nlp','seq',['seq2seq','bahdanau','bpe']],
['sparse-transformers',2019,'Generating Long Sequences with Sparse Transformers','Sparse Transformer','efficiency','attn',['transformer']],
['gopher',2021,'Scaling Language Models: Methods, Analysis & Insights from Training Gopher','Gopher','llm','scale',['gpt3','scaling-laws']],
['lamda',2022,'LaMDA: Language Models for Dialog Applications','LaMDA','llm','align',['transformer','gpt3']],
['opt',2022,'OPT: Open Pre-trained Transformer Language Models','OPT','llm','open',['gpt3']],
['bloom',2022,'BLOOM: A 176B-Parameter Open-Access Multilingual Language Model','BLOOM','llm','open',['gpt3','opt']],
['flan-t5',2022,'Scaling Instruction-Finetuned Language Models (Flan-T5)','Flan-T5','llm','align',['flan','t5','cot']],
['general-assistant',2021,'A General Language Assistant as a Laboratory for Alignment','범용 어시스턴트','llm','align',['gpt3']],
['anthropic-hh',2022,'Training a Helpful and Harmless Assistant with RLHF','HH-RLHF','llm','align',['instructgpt','summarize-hf','general-assistant']],
['glide',2022,'GLIDE: Text-Guided Diffusion for Image Generation and Editing','GLIDE','generative','diffusion',['ddpm','cfg','clip']],
['dalle2',2022,'Hierarchical Text-Conditional Image Generation with CLIP Latents (DALL·E 2)','DALL·E 2','generative','diffusion',['clip','glide','ddpm']],
['cpc',2018,'Representation Learning with Contrastive Predictive Coding','CPC','vision','selfsup',['word2vec','backprop']],
['arc-bench',2018,'Think you have Solved Question Answering? Try ARC','ARC','interp','eval',['elmo']],
['hellaswag',2019,'HellaSwag: Can a Machine Really Finish Your Sentence?','HellaSwag','interp','eval',['bert','gpt2']],
['math-dataset',2021,'Measuring Mathematical Problem Solving With the MATH Dataset','MATH','interp','eval',['gpt3','gsm8k']],
['bbh',2022,'Challenging BIG-Bench Tasks and Whether Chain-of-Thought Can Solve Them','BIG-Bench Hard','interp','eval',['bigbench','cot']],
['mbpp',2021,'Program Synthesis with Large Language Models (MBPP)','MBPP','code','bench',['humaneval']],
['foundation-models',2021,'On the Opportunities and Risks of Foundation Models','파운데이션 모델 보고서','interp','eval',['gpt3','bert','clip']],

// ════════ 4차 확장 — 참고문헌 채굴 2회차 ════════
['diffusion-original',2015,'Deep Unsupervised Learning using Nonequilibrium Thermodynamics','확산 모델의 원조','generative','diffusion',['vae','backprop']],
['grad-checkpointing',2016,'Training Deep Nets with Sublinear Memory Cost','gradient 체크포인팅','efficiency','serve',['backprop','resnet']],
['mixed-precision',2017,'Mixed Precision Training','혼합 정밀도 학습','efficiency','serve',['adam','batchnorm']],
['scaling-predictable',2017,'Deep Learning Scaling is Predictable, Empirically','예측 가능한 스케일링','llm','scale',['resnet','lstm']],
['lm-limits',2016,'Exploring the Limits of Language Modeling','언어모델의 한계 탐색','nlp','seq',['lstm','nnlm']],
['decoder-only-wiki',2018,'Generating Wikipedia by Summarizing Long Sequences','decoder-only Transformer','llm','core',['transformer']],
['glue',2018,'GLUE: A Multi-Task Benchmark for Natural Language Understanding','GLUE','interp','eval',['elmo']],
['superglue',2019,'SuperGLUE: A Stickier Benchmark for General-Purpose Language Understanding','SuperGLUE','interp','eval',['glue','bert']],
['squad',2016,'SQuAD: 100,000+ Questions for Machine Comprehension of Text','SQuAD','interp','eval',['lstm','word2vec']],

// ════════ 5차 확장 — 참고문헌 채굴 3회차 ════════
['dropout-2012',2012,'Improving Neural Networks by Preventing Co-adaptation of Feature Detectors','드롭아웃 최초 보고','foundations','stabilize',['backprop','alexnet']],
['straight-through',2013,'Estimating or Propagating Gradients Through Stochastic Neurons','Straight-Through 추정기','foundations','learning',['backprop']],
['billion-word',2013,'One Billion Word Benchmark for Measuring Progress in Language Modeling','10억 단어 벤치마크','interp','eval',['nnlm']],
['rezende-vae',2014,'Stochastic Backpropagation and Approximate Inference in Deep Generative Models','확률적 역전파','generative','vae',['vae','backprop']],
['caffe',2014,'Caffe: Convolutional Architecture for Fast Feature Embedding','Caffe','efficiency','serve',['alexnet']],
['sgdr',2016,'SGDR: Stochastic Gradient Descent with Warm Restarts','코사인 스케줄 · warm restart','theory','optim',['adam','resnet']],
['wide-resnet',2016,'Wide Residual Networks','Wide ResNet','vision','cnn',['resnet']],
['ulmfit',2018,'Universal Language Model Fine-tuning for Text Classification (ULMFiT)','ULMFiT','nlp','repr',['lstm','elmo']],
['transformer-xl',2019,'Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context','Transformer-XL','llm','context',['transformer']],
['albert',2019,'ALBERT: A Lite BERT for Self-supervised Learning of Language Representations','ALBERT','llm','pretrain',['bert']],
['spanbert',2019,'SpanBERT: Improving Pre-training by Representing and Predicting Spans','SpanBERT','llm','pretrain',['bert','roberta']],
['distilbert',2019,'DistilBERT, a Distilled Version of BERT','DistilBERT','efficiency','quant',['bert','distillation']],
['meena',2020,'Towards a Human-like Open-Domain Chatbot (Meena)','Meena','llm','align',['transformer','seq2seq']],
['gpipe',2019,'GPipe: Efficient Training of Giant Neural Networks using Pipeline Parallelism','GPipe','efficiency','serve',['resnet','transformer']],
['gshard',2020,'GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding','GShard','llm','scale',['moe-shazeer','transformer']],
['mt5',2020,'mT5: A Massively Multilingual Pre-trained Text-to-Text Transformer','mT5','llm','pretrain',['t5','sentencepiece']],
['jukebox',2020,'Jukebox: A Generative Model for Music','Jukebox','speech','codec',['vqvae','sparse-transformers']],
['generative-scaling',2020,'Scaling Laws for Autoregressive Generative Modeling','생성모델 스케일링 법칙','llm','scale',['scaling-laws','gpt3']],
['prompt-tuning',2021,'The Power of Scale for Parameter-Efficient Prompt Tuning','Prompt Tuning','efficiency','peft',['prefix-tuning','t5']],
['t0',2021,'Multitask Prompted Training Enables Zero-Shot Task Generalization (T0)','T0','llm','align',['t5','decanlp']],
['laion400m',2021,'LAION-400M: Open Dataset of CLIP-Filtered Image-Text Pairs','LAION-400M','data','corpus',['clip']],
['agent-alignment',2021,'Alignment of Language Agents','언어 에이전트의 정렬','privacy','safety',['ethical-risks','gpt3']],
['mt-nlg',2022,'Using DeepSpeed and Megatron to Train Megatron-Turing NLG 530B','MT-NLG 530B','llm','scale',['megatron','zero','gpt3']],
['zero-shot-cot',2022,'Large Language Models are Zero-Shot Reasoners','Zero-shot CoT','agent','reason',['cot','gpt3']],
['rethinking-demos',2022,'Rethinking the Role of Demonstrations: What Makes In-Context Learning Work?','시연의 역할 재고','interp','interp',['gpt3','induction-heads']],
['coca',2022,'CoCa: Contrastive Captioners are Image-Text Foundation Models','CoCa','multimodal','contrastive',['clip','blip']],
['florence',2021,'Florence: A New Foundation Model for Computer Vision','Florence','multimodal','contrastive',['clip','swin']],
['palm-e',2023,'PaLM-E: An Embodied Multimodal Language Model','PaLM-E','robotics','vla',['palm','vit','rt1']],

// ════════ 6차 확장 — 참고문헌 채굴 4회차 ════════
['gru',2014,'Learning Phrase Representations using RNN Encoder-Decoder (GRU)','GRU','nlp','seq',['lstm','seq2seq']],
['dqn-2013',2013,'Playing Atari with Deep Reinforcement Learning','DQN 최초 보고','rl','value',['backprop','alexnet']],
['lsun',2015,'LSUN: Construction of a Large-scale Image Dataset with Humans in the Loop','LSUN','data','corpus',['imagenet']],
['sentiment-neuron',2017,'Learning to Generate Reviews and Discovering Sentiment','감성 뉴런','interp','interp',['lstm','word2vec']],
['swish',2017,'Searching for Activation Functions (Swish · SiLU)','Swish · SiLU','foundations','stabilize',['gelu','backprop']],
['kinetics',2017,'The Kinetics Human Action Video Dataset','Kinetics','video','understand',['ucf101','imagenet']],
['cola',2018,'Neural Network Acceptability Judgments (CoLA)','CoLA','interp','eval',['lstm','glue']],
['commonsense-lm',2018,'A Simple Method for Commonsense Reasoning','상식 추론과 언어모델','interp','eval',['lstm','nnlm']],
['biggan',2019,'Large Scale GAN Training for High Fidelity Natural Image Synthesis (BigGAN)','BigGAN','generative','gan',['dcgan','wgan','stylegan']],
['reward-modeling',2018,'Scalable Agent Alignment via Reward Modeling: A Research Direction','보상 모델링 연구 방향','rl','rlhf',['rlhf-prefs','dqn']],
['universal-transformer',2018,'Universal Transformers','Universal Transformer','llm','core',['transformer','lstm']],
['record',2018,'ReCoRD: Bridging the Gap between Human and Machine Commonsense Reading','ReCoRD','interp','eval',['squad','bert']],
['socialiqa',2019,'SocialIQA: Commonsense Reasoning about Social Interactions','SocialIQA','interp','eval',['bert','hellaswag']],
['energy-policy',2019,'Energy and Policy Considerations for Deep Learning in NLP','에너지와 정책','llm','scale',['transformer','bert']],
['carbon-quantify',2019,'Quantifying the Carbon Emissions of Machine Learning','탄소 배출 정량화','llm','scale',['energy-policy']],
['vqvae2',2019,'Generating Diverse High-Fidelity Images with VQ-VAE-2','VQ-VAE-2','generative','vae',['vqvae']],
['score-improved',2020,'Improved Techniques for Training Score-Based Generative Models','스코어 모델 개선','generative','diffusion',['diffusion-original','vae']],
['realtoxicity',2020,'RealToxicityPrompts: Evaluating Neural Toxic Degeneration','RealToxicityPrompts','privacy','safety',['gpt2','the-pile']],
['diffusion-beats-gan',2021,'Diffusion Models Beat GANs on Image Synthesis','확산이 GAN을 이기다','generative','diffusion',['ddpm','biggan','ddim']],
['beit',2021,'BEiT: BERT Pre-Training of Image Transformers','BEiT','vision','vit',['vit','bert','vqvae']],
['moe-efficient',2021,'Efficient Large Scale Language Modeling with Mixtures of Experts','대규모 MoE 언어모델','llm','scale',['gshard','switch']],
['simvlm',2021,'SimVLM: Simple Visual Language Model Pretraining with Weak Supervision','SimVLM','multimodal','vlm',['clip','t5']],
['webgpt',2021,'WebGPT: Browser-assisted Question-answering with Human Feedback','WebGPT','agent','tool',['gpt3','summarize-hf']],
['quantify-memorization',2022,'Quantifying Memorization Across Neural Language Models','암기의 정량화','privacy','attack',['extracting-training-data','dedup']],
['agieval',2023,'AGIEval: A Human-Centric Benchmark for Evaluating Foundation Models','AGIEval','interp','eval',['mmlu','gpt4']],

// ════════ 7차 확장 — 참고문헌 채굴 5회차 ════════
['memory-networks',2014,'Memory Networks','Memory Networks','llm','core',['lstm','seq2seq']],
['babi',2015,'Towards AI-Complete Question Answering: A Set of Prerequisite Toy Tasks (bAbI)','bAbI','interp','eval',['memory-networks','lstm']],
['concrete-safety',2016,'Concrete Problems in AI Safety','구체적 AI 안전 문제','privacy','safety',['dqn','backprop']],
['real-nvp',2016,'Density Estimation using Real NVP','Real NVP','generative','vae',['vae']],
['lambada',2016,'The LAMBADA Dataset: Word Prediction Requiring a Broad Discourse Context','LAMBADA','interp','eval',['lstm','nnlm']],
['race',2017,'RACE: Large-scale ReAding Comprehension Dataset From Examinations','RACE','interp','eval',['squad','lstm']],
['datasheets',2018,'Datasheets for Datasets','데이터셋 명세서','data','curate',['imagenet']],
['debate',2018,'AI Safety via Debate','토론을 통한 AI 안전','privacy','safety',['rlhf-prefs','alphago']],
['iterated-amplification',2018,'Supervising Strong Learners by Amplifying Weak Experts','반복 증폭','privacy','safety',['rlhf-prefs','debate']],
['squad2',2018,'Know What You Don\'t Know: Unanswerable Questions for SQuAD (SQuAD 2.0)','SQuAD 2.0','interp','eval',['squad','bert']],
['xlm',2019,'Cross-lingual Language Model Pretraining (XLM)','XLM','llm','pretrain',['bert','bpe']],
['bias-in-generation',2019,'The Woman Worked as a Babysitter: On Biases in Language Generation','생성의 편향','privacy','safety',['gpt2','elmo']],
['huggingface',2019,'HuggingFace\'s Transformers: State-of-the-art Natural Language Processing','Transformers 라이브러리','efficiency','serve',['bert','gpt2','caffe']],
['vtab',2019,'A Large-scale Study of Representation Learning with the Visual Task Adaptation Benchmark','VTAB','interp','eval',['imagenet','resnet']],
['moco-v2',2020,'Improved Baselines with Momentum Contrastive Learning (MoCo v2)','MoCo v2','vision','selfsup',['moco','simclr']],
['linformer',2020,'Linformer: Self-Attention with Linear Complexity','Linformer','efficiency','attn',['transformer','sparse-attn']],
['stereoset',2020,'StereoSet: Measuring Stereotypical Bias in Pretrained Language Models','StereoSet','privacy','safety',['bert','gpt2']],
['safety-recipes',2020,'Recipes for Safety in Open-domain Chatbots','대화 안전 레시피','privacy','safety',['meena','bias-in-generation']],
['pangu-alpha',2021,'PanGu-α: Large-scale Autoregressive Pretrained Chinese Language Models','PanGu-α','llm','open',['gpt3','megatron']],
['vit-scaling',2021,'Scaling Vision Transformers','ViT 스케일링','vision','vit',['vit','scaling-laws']],
['stochastic-parrots-risk',2021,'Understanding the Capabilities, Limitations, and Societal Impact of LLMs','LLM 사회적 영향 보고','privacy','safety',['gpt3','ethical-risks']],
['zero-shot-planner',2022,'Language Models as Zero-Shot Planners','Zero-Shot Planner','robotics','vla',['gpt3','saycan']],
['minerva',2022,'Solving Quantitative Reasoning Problems with Language Models (Minerva)','Minerva','agent','reason',['palm','cot','math-dataset']],
['t5x',2022,'Scaling Up Models and Data with t5x and seqio','t5x · seqio','efficiency','serve',['t5','megatron']],
['sparks-agi',2023,'Sparks of Artificial General Intelligence: Early Experiments with GPT-4','AGI의 불꽃','interp','eval',['gpt4','emergent']],

// ════════ 8차 확장 — 참고문헌 채굴 6회차 ════════
['ntm',2014,'Neural Turing Machines','Neural Turing Machine','llm','core',['lstm','memory-networks']],
['nice',2014,'NICE: Non-linear Independent Components Estimation','NICE','generative','vae',['vae','backprop']],
['intriguing',2013,'Intriguing Properties of Neural Networks','적대적 예제의 발견','privacy','attack',['alexnet','backprop']],
['fgsm',2014,'Explaining and Harnessing Adversarial Examples (FGSM)','FGSM','privacy','attack',['intriguing','alexnet']],
['gae',2015,'High-Dimensional Continuous Control Using Generalized Advantage Estimation','GAE','rl','policy',['trpo']],
['pixelrnn',2016,'Pixel Recurrent Neural Networks','PixelRNN · PixelCNN','generative','vae',['lstm','vae']],
['tensorflow',2016,'TensorFlow: Large-Scale Machine Learning on Heterogeneous Systems','TensorFlow','efficiency','serve',['caffe','backprop']],
['wikitext',2016,'Pointer Sentinel Mixture Models (WikiText)','WikiText','interp','eval',['lstm','nnlm']],
['ms-marco',2016,'MS MARCO: A Human Generated Machine Reading Comprehension Dataset','MS MARCO','ir','dense',['squad']],
['rl-summarization',2017,'A Deep Reinforced Model for Abstractive Summarization','강화학습 요약','nlp','seq',['seq2seq','bahdanau']],
['deeper-self-attention',2018,'Character-Level Language Modeling with Deeper Self-Attention','깊은 self-attention 문자 LM','llm','core',['transformer','lstm']],
['qanet',2018,'QANet: Combining Local Convolution with Global Self-Attention','QANet','ir','dense',['squad','transformer']],
['inception-score-note',2018,'A Note on the Inception Score','Inception Score 비판','generative','gan',['gan','dcgan']],
['grover',2019,'Defending Against Neural Fake News (Grover)','Grover','privacy','safety',['gpt2','bert']],
['cmc',2019,'Contrastive Multiview Coding','Contrastive Multiview Coding','vision','selfsup',['cpc','resnet']],
['one-epoch',2019,'One Epoch Is All You Need','1 epoch 만으로 충분하다','llm','scale',['gpt2','transformer']],
['anli',2020,'Adversarial NLI: A New Benchmark for Natural Language Understanding','Adversarial NLI','interp','eval',['glue','bert']],
['bias-survey',2020,'Language (Technology) is Power: A Critical Survey of Bias in NLP','NLP 편향 비판적 개관','privacy','safety',['bias-in-generation','stereoset']],
['df-gan',2020,'DF-GAN: A Simple and Effective Baseline for Text-to-Image Synthesis','DF-GAN','generative','gan',['stylegan','biggan']],
['iddpm',2021,'Improved Denoising Diffusion Probabilistic Models','Improved DDPM','generative','diffusion',['ddpm','ddim']],
['done-with-imagenet',2020,'Are We Done with ImageNet?','ImageNet 라벨 재검토','interp','eval',['imagenet','resnet']],
['imagen-video',2022,'Imagen Video: High Definition Video Generation with Diffusion Models','Imagen Video','video','generate',['imagen','video-diffusion','cascaded-diffusion']],
['glm-130b',2022,'GLM-130B: An Open Bilingual Pre-trained Model','GLM-130B','llm','open',['gpt3','megatron']],
['bloomz',2022,'Crosslingual Generalization through Multitask Finetuning (BLOOMZ · mT0)','BLOOMZ · mT0','llm','align',['bloom','mt5','t0']],
['santacoder',2023,'SantaCoder: Don\'t Reach for the Stars!','SantaCoder','code','pretrain',['starcoder','codet5']],
['pythia',2023,'Pythia: A Suite for Analyzing Large Language Models Across Training and Scaling','Pythia','interp','interp',['gpt-neox','the-pile']],
['palm2',2023,'PaLM 2 Technical Report','PaLM 2','llm','pretrain',['palm','chinchilla']],
['gemini',2023,'Gemini: A Family of Highly Capable Multimodal Models','Gemini','multimodal','vlm',['palm2','gpt4','flamingo']],
['decanlp',2018,'The Natural Language Decathlon: Multitask Learning as Question Answering','decaNLP','interp','eval',['seq2seq','elmo']],
['xlnet',2019,'XLNet: Generalized Autoregressive Pretraining for Language Understanding','XLNet','llm','pretrain',['bert','transformer']],
['glu-variants',2020,'GLU Variants Improve Transformer (SwiGLU)','SwiGLU','llm','core',['transformer','t5']],
['scratchpad',2021,'Show Your Work: Scratchpads for Intermediate Computation','Scratchpad','agent','reason',['transformer','gpt3']],
['retro',2021,'Improving Language Models by Retrieving from Trillions of Tokens (RETRO)','RETRO','ir','dense',['rag','realm','gopher']],
['truthfulqa',2021,'TruthfulQA: Measuring How Models Mimic Human Falsehoods','TruthfulQA','interp','eval',['gpt3']],
['boolq',2019,'BoolQ: Exploring the Surprising Difficulty of Natural Yes/No Questions','BoolQ','interp','eval',['bert','glue']],
['triviaqa',2017,'TriviaQA: A Large Scale Distantly Supervised Challenge Dataset','TriviaQA','interp','eval',['seq2seq']],
['openbookqa',2018,'Can a Suit of Armor Conduct Electricity? Open Book Question Answering','OpenBookQA','interp','eval',['arc-bench']],
['carbon',2021,'Carbon Emissions and Large Neural Network Training','학습의 탄소 배출','llm','scale',['gpt3','scaling-laws']],
['ethical-risks',2021,'Ethical and Social Risks of Harm from Language Models','언어모델의 위해 분류','privacy','safety',['gpt3','gopher']],
['gpt-neox',2022,'GPT-NeoX-20B: An Open-Source Autoregressive Language Model','GPT-NeoX-20B','llm','open',['gpt3','the-pile']],
['ul2',2022,'UL2: Unifying Language Learning Paradigms','UL2','llm','pretrain',['t5','bart','xlnet']],
['cascaded-diffusion',2021,'Cascaded Diffusion Models for High Fidelity Image Generation','Cascaded Diffusion','generative','diffusion',['ddpm','sr3']],
['sr3',2021,'Image Super-Resolution via Iterative Refinement (SR3)','SR3','generative','diffusion',['ddpm']],
['coco-captions',2015,'Microsoft COCO Captions: Data Collection and Evaluation Server','COCO Captions','data','corpus',['imagenet']],
['ucf101',2012,'UCF101: A Dataset of 101 Human Action Classes From Videos in The Wild','UCF101','video','understand',['imagenet']],

// ════════ 9차 확장 — 참고문헌 채굴 7회차 ════════
['cpc-v2',2019,'Data-Efficient Image Recognition with Contrastive Predictive Coding','CPC v2','vision','selfsup',['cpc','resnet']],
['pirl',2019,'Self-Supervised Learning of Pretext-Invariant Representations','PIRL','vision','selfsup',['cpc','resnet']],
['simclr-v2',2020,'Big Self-Supervised Models are Strong Semi-Supervised Learners','SimCLR v2','vision','selfsup',['simclr','distillation']],
['bit',2019,'Big Transfer (BiT): General Visual Representation Learning','BiT 전이학습','vision','cnn',['resnet','imagenet']],
['imagenet-v2',2019,'Do ImageNet Classifiers Generalize to ImageNet?','ImageNet 재현성','interp','eval',['imagenet','resnet']],
['instance-norm',2016,'Instance Normalization: The Missing Ingredient for Fast Stylization','Instance 정규화','foundations','stabilize',['batchnorm']],
['autoaugment',2018,'AutoAugment: Learning Augmentation Policies from Data','AutoAugment','vision','cnn',['resnet','imagenet']],
['lars',2017,'Large Batch Training of Convolutional Networks','LARS 대배치 학습','efficiency','serve',['resnet','batchnorm']],
['one-weird-trick',2014,'One weird trick for parallelizing convolutional neural networks','병렬화의 한 수','efficiency','serve',['alexnet']],
['elu',2015,'Fast and Accurate Deep Network Learning by Exponential Linear Units','ELU 활성함수','foundations','stabilize',['batchnorm']],
['fid',2017,'GANs Trained by a Two Time-Scale Update Rule Converge to a Local Nash Equilibrium','FID · TTUR','generative','gan',['gan','dcgan']],
['improved-gan',2016,'Improved Techniques for Training GANs','GAN 학습 기법 개선','generative','gan',['gan','dcgan']],
['eval-generative-note',2015,'A note on the evaluation of generative models','생성모델 평가 비판','generative','gan',['gan','vae']],
['pixelcnn-pp',2017,'PixelCNN++: Improving the PixelCNN with Discretized Logistic Mixture Likelihood','PixelCNN++','generative','vae',['pixelrnn']],
['vdm',2021,'Variational Diffusion Models','변분 확산모델','generative','diffusion',['ddpm','vae']],
['sdedit',2021,'SDEdit: Guided Image Synthesis and Editing with Stochastic Differential Equations','SDEdit','generative','diffusion',['score-sde','ddpm']],
['textual-inversion',2022,'An Image is Worth One Word: Personalizing Text-to-Image Generation using Textual Inversion','Textual Inversion','generative','diffusion',['ldm']],
['parti',2022,'Scaling Autoregressive Models for Content-Rich Text-to-Image Generation','Parti','generative','vae',['dalle','vqgan']],
['make-a-scene',2022,'Make-A-Scene: Scene-Based Text-to-Image Generation with Human Priors','Make-A-Scene','generative','vae',['dalle','vqgan']],
['nucleus-sampling',2019,'The Curious Case of Neural Text Degeneration','뉴클리어스 샘플링','llm','core',['gpt2']],
['ctrl',2019,'CTRL: A Conditional Transformer Language Model for Controllable Generation','CTRL','llm','pretrain',['gpt2']],
['natural-instructions',2021,'Cross-Task Generalization via Natural Language Crowdsourcing Instructions','Natural Instructions','llm','align',['bart']],
['super-natural-instructions',2022,'Super-NaturalInstructions: Generalization via Declarative Instructions on 1600+ NLP Tasks','Super-NaturalInstructions','llm','align',['natural-instructions','t0']],
['flan-collection',2023,'The Flan Collection: Designing Data and Methods for Effective Instruction Tuning','Flan Collection','llm','align',['flan','t0']],
['ul2r',2022,'Transcending Scaling Laws with 0.1% Extra Compute','UL2R · U-PaLM','llm','scale',['ul2','palm']],
['st-moe',2022,'ST-MoE: Designing Stable and Transferable Sparse Expert Models','ST-MoE','efficiency','serve',['switch','moe-shazeer']],
['memory-efficient-attn',2021,'Self-attention Does Not Need O(n^2) Memory','메모리 효율 attention','efficiency','attn',['transformer']],
['prompt-survey',2021,'Pre-train, Prompt, and Predict: A Systematic Survey of Prompting Methods','프롬프팅 서베이','llm','align',['gpt3']],
['commonsenseqa',2018,'CommonsenseQA: A Question Answering Challenge Targeting Commonsense Knowledge','CommonsenseQA','interp','eval',['bert']],
['multinli',2017,'A Broad-Coverage Challenge Corpus for Sentence Understanding through Inference','MultiNLI','interp','eval',['seq2seq']],
['mt-dnn',2019,'Multi-Task Deep Neural Networks for Natural Language Understanding','MT-DNN','nlp','repr',['bert','glue']],
['pointer-generator',2017,'Get To The Point: Summarization with Pointer-Generator Networks','포인터 생성 요약','nlp','seq',['seq2seq','bahdanau']],
['pipedream',2018,'PipeDream: Fast and Efficient Pipeline Parallel DNN Training','PipeDream','efficiency','serve',['resnet','one-weird-trick']],
['gspmd',2021,'GSPMD: General and Scalable Parallelization for ML Computation Graphs','GSPMD','efficiency','serve',['gshard']],
['quantization-survey',2021,'A Survey of Quantization Methods for Efficient Neural Network Inference','양자화 서베이','efficiency','quant',['distillation']],
['incoder',2022,'InCoder: A Generative Model for Code Infilling and Synthesis','InCoder','code','pretrain',['humaneval']],
['fim',2022,'Efficient Training of Language Models to Fill in the Middle','FIM 중간 채우기','code','pretrain',['humaneval','incoder']],
['apps',2021,'Measuring Coding Challenge Competence With APPS','APPS 벤치마크','code','bench',['humaneval']],
['red-teaming-lm',2022,'Red Teaming Language Models with Language Models','LM 으로 LM 레드팀','privacy','safety',['instructgpt']],
['anti-muslim-bias',2021,'Persistent Anti-Muslim Bias in Large Language Models','지속되는 반무슬림 편향','privacy','safety',['gpt3']],

// ════════ 10차 확장 — 참고문헌 채굴 8회차 ════════
['billion-scale-ssl',2019,'Billion-scale semi-supervised learning for image classification','10억장 준지도 학습','vision','cnn',['resnet','imagenet']],
['uda',2019,'Unsupervised Data Augmentation for Consistency Training','UDA 일관성 학습','foundations','data',['autoaugment','bert']],
['noisy-student',2019,'Self-training with Noisy Student improves ImageNet classification','Noisy Student','vision','cnn',['efficientnet','autoaugment']],
['rotnet',2018,'Unsupervised Representation Learning by Predicting Image Rotations','회전 예측 자기지도','vision','selfsup',['resnet','imagenet']],
['amdim',2019,'Learning Representations by Maximizing Mutual Information Across Views','AMDIM','vision','selfsup',['cpc']],
['bigbigan',2019,'Large Scale Adversarial Representation Learning','BigBiGAN','generative','gan',['biggan','gan']],
['progressive-gan',2017,'Progressive Growing of GANs for Improved Quality, Stability, and Variation','Progressive GAN','generative','gan',['dcgan','wgan']],
['styleclip',2021,'StyleCLIP: Text-Driven Manipulation of StyleGAN Imagery','StyleCLIP','generative','gan',['stylegan','clip']],
['gumbel-softmax',2016,'Categorical Reparameterization with Gumbel-Softmax','Gumbel-Softmax','foundations','learning',['vae']],
['reformer',2020,'Reformer: The Efficient Transformer','Reformer','efficiency','attn',['transformer']],
['unilm',2019,'Unified Language Model Pre-training for Natural Language Understanding and Generation','UniLM','nlp','repr',['bert','transformer']],
['deberta',2020,'DeBERTa: Decoding-enhanced BERT with Disentangled Attention','DeBERTa','nlp','repr',['bert','roberta']],
['ernie',2019,'ERNIE: Enhanced Representation through Knowledge Integration','ERNIE','nlp','repr',['bert']],
['stilts',2018,'Sentence Encoders on STILTs: Supplementary Training on Intermediate Labeled-data Tasks','STILTs','nlp','repr',['bert','glue']],
['tied-embeddings',2016,'Using the Output Embedding to Improve Language Models','입출력 임베딩 묶기','nlp','repr',['nnlm']],
['neural-summarization',2015,'A Neural Attention Model for Abstractive Sentence Summarization','신경 주의 요약','nlp','seq',['seq2seq','bahdanau']],
['abstractive-rnn',2016,'Abstractive Text Summarization Using Sequence-to-Sequence RNNs and Beyond','seq2seq 추상 요약','nlp','seq',['seq2seq','bahdanau']],
['opt-iml',2022,'OPT-IML: Scaling Language Model Instruction Meta Learning through the Lens of Generalization','OPT-IML','llm','align',['opt','flan']],
['unnatural-instructions',2022,'Unnatural Instructions: Tuning Language Models with (Almost) No Human Labor','Unnatural Instructions','llm','align',['self-instruct']],
['glam',2021,'GLaM: Efficient Scaling of Language Models with Mixture-of-Experts','GLaM','efficiency','serve',['switch','gpt3']],
['scale-efficiently',2021,'Scale Efficiently: Insights from Pre-training and Fine-tuning Transformers','효율적 스케일링','llm','scale',['t5','scaling-laws']],
['closed-book-qa',2020,'How Much Knowledge Can You Pack Into the Parameters of a Language Model?','닫힌 책 QA','llm','core',['t5']],
['term-freq-reasoning',2022,'Impact of Pretraining Term Frequencies on Few-Shot Reasoning','용어 빈도와 추론','interp','interp',['gpt3']],
['good-in-context',2021,'What Makes Good In-Context Examples for GPT-3?','좋은 문맥 예시','llm','core',['gpt3']],
['inner-monologue',2022,'Inner Monologue: Embodied Reasoning through Planning with Language Models','Inner Monologue','agent','reason',['saycan','cot']],
['sparrow',2022,'Improving alignment of dialogue agents via targeted human judgements','Sparrow','llm','align',['instructgpt','chinchilla']],
['cm3',2022,'CM3: A Causal Masked Multimodal Model of the Internet','CM3','multimodal','vlm',['transformer','vqvae']],
['visual-semantic-embed',2014,'Unifying Visual-Semantic Embeddings with Multimodal Neural Language Models','시각-언어 임베딩 통합','multimodal','contrastive',['word2vec','lstm']],
['convirt',2020,'Contrastive Learning of Medical Visual Representations from Paired Images and Text','ConVIRT','multimodal','contrastive',['cpc','bert']],
['deepmind-lab',2016,'DeepMind Lab','DeepMind Lab','rl','world',['dqn']],
['senteval',2018,'SentEval: An Evaluation Toolkit for Universal Sentence Representations','SentEval','interp','eval',['glove']],
['cbt',2015,'The Goldilocks Principle: Reading Children\'s Books with Explicit Memory Representations','Children\'s Book Test','interp','eval',['memory-networks']],
['newsqa',2016,'NewsQA: A Machine Comprehension Dataset','NewsQA','interp','eval',['squad']],
['cifar-10-v2',2018,'Do CIFAR-10 Classifiers Generalize to CIFAR-10?','CIFAR-10 재현성','interp','eval',['resnet']],
['adversarial-triggers',2019,'Universal Adversarial Triggers for Attacking and Analyzing NLP','보편 적대 트리거','privacy','attack',['fgsm','bert']],
['sentiment-bias',2019,'Reducing Sentiment Bias in Language Models via Counterfactual Evaluation','감성 편향 줄이기','privacy','safety',['gpt2']],
['palms',2021,'Process for Adapting Language Models to Society (PALMS) with Values-Targeted Datasets','PALMS','privacy','safety',['gpt3']],
['malicious-use',2018,'The Malicious Use of Artificial Intelligence: Forecasting, Prevention, and Mitigation','AI 의 악용','privacy','safety',['gan','fgsm']],
['gender-bias-amplification',2017,'Men Also Like Shopping: Reducing Gender Bias Amplification using Corpus-level Constraints','성별 편향 증폭','privacy','safety',['word2vec']],
['adadelta',2012,'ADADELTA: An Adaptive Learning Rate Method','ADADELTA','foundations','learning',['backprop']],

// ════════ 11차 확장 — 실무 분야별 랜드마크 ════════
['dann',2015,'Domain-Adversarial Training of Neural Networks','DANN 도메인 적대 학습','foundations','transfer',['backprop','gan']],
['adda',2017,'Adversarial Discriminative Domain Adaptation','ADDA','foundations','transfer',['dann','gan']],
['cycada',2017,'CyCADA: Cycle-Consistent Adversarial Domain Adaptation','CyCADA','foundations','transfer',['dann','cyclegan']],
['deep-coral',2016,'Deep CORAL: Correlation Alignment for Deep Domain Adaptation','Deep CORAL','foundations','transfer',['alexnet']],
['tent',2021,'Tent: Fully Test-Time Adaptation by Entropy Minimization','TENT 시험시 적응','foundations','transfer',['batchnorm','dann']],
['yolov3',2018,'YOLOv3: An Incremental Improvement','YOLOv3','vision','detect',['yolo','fpn','resnet']],
['fcos',2019,'FCOS: Fully Convolutional One-Stage Object Detection','FCOS 앵커 없는 검출','vision','detect',['focal-loss','fpn']],
['centernet',2019,'Objects as Points (CenterNet)','CenterNet','vision','detect',['fcos','unet']],
['cascade-rcnn',2018,'Cascade R-CNN: Delving into High Quality Object Detection','Cascade R-CNN','vision','detect',['faster-rcnn']],
['efficientdet',2020,'EfficientDet: Scalable and Efficient Object Detection','EfficientDet','vision','detect',['efficientnet','fpn']],
['deformable-detr',2020,'Deformable DETR: Deformable Transformers for End-to-End Object Detection','Deformable DETR','vision','detect',['detr']],
['dino-detr',2022,'DINO: DETR with Improved DeNoising Anchor Boxes for End-to-End Object Detection','DINO-DETR','vision','detect',['deformable-detr','detr']],
['owl-vit',2022,'Simple Open-Vocabulary Object Detection with Vision Transformers','OWL-ViT 개방어휘 검출','vision','detect',['vit','clip']],
['grounding-dino',2023,'Grounding DINO: Marrying DINO with Grounded Pre-Training for Open-Set Object Detection','Grounding DINO','vision','detect',['dino-detr','clip']],
['sort',2016,'Simple Online and Realtime Tracking (SORT)','SORT 추적','vision','detect',['faster-rcnn']],
['deepsort',2017,'Simple Online and Realtime Tracking with a Deep Association Metric','DeepSORT','vision','detect',['sort','resnet']],
['bytetrack',2021,'ByteTrack: Multi-Object Tracking by Associating Every Detection Box','ByteTrack','vision','detect',['deepsort','yolo']],
['pspnet',2017,'Pyramid Scene Parsing Network (PSPNet)','PSPNet','vision','seg',['fcn','resnet']],
['deeplabv3plus',2018,'Encoder-Decoder with Atrous Separable Convolution for Semantic Image Segmentation','DeepLabv3+','vision','seg',['deeplab','unet']],
['panoptic',2019,'Panoptic Segmentation','파놉틱 분할','vision','seg',['mask-rcnn','fcn']],
['maskformer',2021,'Per-Pixel Classification is Not All You Need for Semantic Segmentation','MaskFormer','vision','seg',['detr','panoptic']],
['mask2former',2022,'Masked-attention Mask Transformer for Universal Image Segmentation','Mask2Former','vision','seg',['maskformer','deformable-detr']],
['segformer',2021,'SegFormer: Simple and Efficient Design for Semantic Segmentation with Transformers','SegFormer','vision','seg',['vit','deeplabv3plus']],
['sam2',2024,'SAM 2: Segment Anything in Images and Videos','SAM 2','vision','seg',['sam']],
['vilbert',2019,'ViLBERT: Pretraining Task-Agnostic Visiolinguistic Representations','ViLBERT','multimodal','vlm',['bert','faster-rcnn']],
['lxmert',2019,'LXMERT: Learning Cross-Modality Encoder Representations from Transformers','LXMERT','multimodal','vlm',['bert','faster-rcnn']],
['vilt',2021,'ViLT: Vision-and-Language Transformer Without Convolution or Region Supervision','ViLT','multimodal','vlm',['vit','vilbert']],
['frozen-vlm',2021,'Multimodal Few-Shot Learning with Frozen Language Models','Frozen','multimodal','vlm',['gpt3','prefix-tuning']],
['instructblip',2023,'InstructBLIP: Towards General-purpose Vision-Language Models with Instruction Tuning','InstructBLIP','multimodal','vlm',['blip2','flan']],
['layoutlm',2019,'LayoutLM: Pre-training of Text and Layout for Document Image Understanding','LayoutLM','multimodal','vlm',['bert']],
['trocr',2021,'TrOCR: Transformer-based Optical Character Recognition with Pre-trained Models','TrOCR','multimodal','vlm',['vit','roberta']],
['donut',2021,'OCR-free Document Understanding Transformer (Donut)','Donut','multimodal','vlm',['swin','bart']],
['nougat',2023,'Nougat: Neural Optical Understanding for Academic Documents','Nougat','multimodal','vlm',['donut','swin']],
['facenet',2015,'FaceNet: A Unified Embedding for Face Recognition and Clustering','FaceNet 삼중항 손실','vision','cnn',['googlenet']],
['arcface',2018,'ArcFace: Additive Angular Margin Loss for Deep Face Recognition','ArcFace','vision','cnn',['facenet','resnet']],
['msp-baseline',2016,'A Baseline for Detecting Misclassified and Out-of-Distribution Examples in Neural Networks','MSP 기준선','interp','trust',['resnet']],
['odin',2017,'Enhancing the Reliability of Out-of-distribution Image Detection in Neural Networks','ODIN','interp','trust',['msp-baseline','fgsm']],
['temperature-scaling',2017,'On Calibration of Modern Neural Networks','현대 신경망의 보정','interp','trust',['resnet','msp-baseline']],
['deep-ensembles',2016,'Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles','딥 앙상블','interp','trust',['dropout']],
['mc-dropout',2015,'Dropout as a Bayesian Approximation: Representing Model Uncertainty in Deep Learning','MC 드롭아웃','interp','trust',['dropout']],
['deep-compression',2015,'Deep Compression: Compressing Deep Neural Networks with Pruning, Trained Quantization and Huffman Coding','Deep Compression','efficiency','quant',['alexnet']],
['lottery-ticket',2018,'The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks','복권 가설','efficiency','quant',['deep-compression']],
['movement-pruning',2020,'Movement Pruning: Adaptive Sparsity by Fine-Tuning','Movement Pruning','efficiency','quant',['lottery-ticket','bert']],
['midas',2019,'Towards Robust Monocular Depth Estimation: Mixing Datasets for Zero-shot Cross-dataset Transfer','MiDaS','vision','dense',['resnet']],
['deepseek-v2',2024,'DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model','DeepSeek-V2 · MLA','efficiency','attn',['switch','llama']],

// ════════ 12차 확장 — 음성 뿌리 · 정형/시계열 · 실무 공백 ════════
['ctc',2006,'Connectionist Temporal Classification: Labelling Unsegmented Sequence Data with Recurrent Neural Networks','CTC 손실','speech','asr',['lstm']],
['rnn-t',2012,'Sequence Transduction with Recurrent Neural Networks (RNN-T)','RNN 트랜스듀서','speech','asr',['ctc','lstm']],
['deep-speech',2014,'Deep Speech: Scaling up end-to-end speech recognition','Deep Speech','speech','asr',['ctc']],
['las',2015,'Listen, Attend and Spell','Listen, Attend and Spell','speech','asr',['seq2seq','bahdanau']],
['wav2vec',2019,'wav2vec: Unsupervised Pre-training for Speech Recognition','wav2vec','speech','asr',['cpc','deep-speech']],
['xgboost',2016,'XGBoost: A Scalable Tree Boosting System','XGBoost','tabular','gbdt',[]],
['lightgbm',2017,'LightGBM: A Highly Efficient Gradient Boosting Decision Tree','LightGBM','tabular','gbdt',['xgboost']],
['catboost',2017,'CatBoost: unbiased boosting with categorical features','CatBoost','tabular','gbdt',['xgboost']],
['tabnet',2019,'TabNet: Attentive Interpretable Tabular Learning','TabNet','tabular','deep',['xgboost','transformer']],
['ft-transformer',2021,'Revisiting Deep Learning Models for Tabular Data','FT-Transformer','tabular','deep',['tabnet','transformer']],
['trees-still-win',2022,'Why do tree-based models still outperform deep learning on tabular data?','나무가 아직 이긴다','tabular','gbdt',['xgboost','ft-transformer']],
['deepar',2017,'DeepAR: Probabilistic Forecasting with Autoregressive Recurrent Networks','DeepAR','tabular','forecast',['lstm']],
['nbeats',2019,'N-BEATS: Neural basis expansion analysis for interpretable time series forecasting','N-BEATS','tabular','forecast',['deepar']],
['informer',2020,'Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting','Informer','tabular','forecast',['transformer','deepar']],
['autoformer',2021,'Autoformer: Decomposition Transformers with Auto-Correlation for Long-Term Series Forecasting','Autoformer','tabular','forecast',['informer']],
['dlinear',2022,'Are Transformers Effective for Time Series Forecasting?','선형 하나면 된다(DLinear)','tabular','forecast',['informer','autoformer']],
['patchtst',2022,'A Time Series is Worth 64 Words: Long-term Forecasting with Transformers','PatchTST','tabular','forecast',['dlinear','vit']],
['padim',2020,'PaDiM: a Patch Distribution Modeling Framework for Anomaly Detection and Localization','PaDiM','interp','trust',['resnet','msp-baseline']],
['patchcore',2021,'Towards Total Recall in Industrial Anomaly Detection (PatchCore)','PatchCore','interp','trust',['padim']],
['apex',2018,'Distributed Prioritized Experience Replay (Ape-X)','Ape-X','rl','value',['dqn']],
['impala',2018,'IMPALA: Scalable Distributed Deep-RL with Importance Weighted Actor-Learner Architectures','IMPALA','rl','policy',['a3c']],
['td3',2018,'Addressing Function Approximation Error in Actor-Critic Methods (TD3)','TD3','rl','policy',['ddpg']],
['monot5',2020,'Document Ranking with a Pretrained Sequence-to-Sequence Model (monoT5)','monoT5 리랭커','ir','late',['t5','monobert']],
['contriever',2021,'Unsupervised Dense Information Retrieval with Contrastive Learning','Contriever','ir','dense',['dpr','cpc']],
['hyde',2022,'Precise Zero-Shot Dense Retrieval without Relevance Labels (HyDE)','HyDE','ir','dense',['contriever','gpt3']],
['self-rag',2023,'Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection','Self-RAG','ir','dense',['rag','instructgpt']],
['bpr',2009,'BPR: Bayesian Personalized Ranking from Implicit Feedback','BPR','recsys','cf',['mf']],
['item2vec',2016,'Item2Vec: Neural Item Embedding for Collaborative Filtering','Item2Vec','recsys','cf',['word2vec','mf']],
['dien',2018,'Deep Interest Evolution Network for Click-Through Rate Prediction','DIEN','recsys','seq',['din','lstm']],
['alpaca-eval',2024,'Length-Controlled AlpacaEval: A Simple Way to Debias Automatic Evaluators','길이 보정 AlpacaEval','interp','eval',['chatbot-arena','instructgpt']],

// ════════ 13차 확장 — CV 학회 SOTA · GitHub 고스타 실무 ════════
['yolov4',2020,'YOLOv4: Optimal Speed and Accuracy of Object Detection','YOLOv4','vision','detect',['yolov3','cutmix']],
['yolox',2021,'YOLOX: Exceeding YOLO Series in 2021','YOLOX','vision','detect',['yolov3','fcos']],
['yolov7',2022,'YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors','YOLOv7','vision','detect',['yolov4','yolox']],
['yolov9',2024,'YOLOv9: Learning What You Want to Learn Using Programmable Gradient Information','YOLOv9','vision','detect',['yolov7']],
['yolov10',2024,'YOLOv10: Real-Time End-to-End Object Detection','YOLOv10','vision','detect',['yolov9','detr']],
['rt-detr',2023,'DETRs Beat YOLOs on Real-time Object Detection (RT-DETR)','RT-DETR','vision','detect',['deformable-detr','yolox']],
['mmdetection',2019,'MMDetection: Open MMLab Detection Toolbox and Benchmark','MMDetection','vision','detect',['faster-rcnn','fpn']],
['craft',2019,'Character Region Awareness for Text Detection (CRAFT)','CRAFT 글자 검출','vision','detect',['unet','fcn']],
['dbnet',2019,'Real-time Scene Text Detection with Differentiable Binarization','DBNet','vision','detect',['fpn','craft']],
['srgan',2016,'Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network','SRGAN','vision','dense',['gan','vgg']],
['esrgan',2018,'ESRGAN: Enhanced Super-Resolution Generative Adversarial Networks','ESRGAN','vision','dense',['srgan']],
['real-esrgan',2021,'Real-ESRGAN: Training Real-World Blind Super-Resolution with Pure Synthetic Data','Real-ESRGAN','vision','dense',['esrgan']],
['swinir',2021,'SwinIR: Image Restoration Using Swin Transformer','SwinIR','vision','dense',['swin','esrgan']],
['codeformer',2022,'Towards Robust Blind Face Restoration with Codebook Lookup Transformer (CodeFormer)','CodeFormer','vision','dense',['vqvae','real-esrgan']],
['hrnet',2019,'Deep High-Resolution Representation Learning for Human Pose Estimation','HRNet','vision','dense',['resnet','openpose']],
['vitpose',2022,'ViTPose: Simple Vision Transformer Baselines for Human Pose Estimation','ViTPose','vision','dense',['vit','hrnet']],
['rtmpose',2023,'RTMPose: Real-Time Multi-Person Pose Estimation based on MMPose','RTMPose','vision','dense',['hrnet','mmdetection']],
['mobilenetv2',2018,'MobileNetV2: Inverted Residuals and Linear Bottlenecks','MobileNetV2','vision','cnn',['mobilenet','resnet']],
['shufflenet',2017,'ShuffleNet: An Extremely Efficient Convolutional Neural Network for Mobile Devices','ShuffleNet','vision','cnn',['mobilenet']],
['repvgg',2021,'RepVGG: Making VGG-style ConvNets Great Again','RepVGG','vision','cnn',['vgg','resnet']],
['mobilevit',2021,'MobileViT: Light-weight, General-purpose, and Mobile-friendly Vision Transformer','MobileViT','vision','cnn',['mobilenetv2','vit']],
['efficientnetv2',2021,'EfficientNetV2: Smaller Models and Faster Training','EfficientNetV2','vision','cnn',['efficientnet']],
['coatnet',2021,'CoAtNet: Marrying Convolution and Attention for All Data Sizes','CoAtNet','vision','vit',['vit','efficientnet']],
['swinv2',2021,'Swin Transformer V2: Scaling Up Capacity and Resolution','Swin V2','vision','vit',['swin']],
['internimage',2022,'InternImage: Exploring Large-Scale Vision Foundation Models with Deformable Convolutions','InternImage','vision','cnn',['convnext','deformable-detr']],
['eva',2022,'EVA: Exploring the Limits of Masked Visual Representation Learning at Scale','EVA','vision','vit',['mae','clip']],
['cutout',2017,'Improved Regularization of Convolutional Neural Networks with Cutout','Cutout','vision','cnn',['dropout','resnet']],
['cutmix',2019,'CutMix: Regularization Strategy to Train Strong Classifiers with Localizable Features','CutMix','vision','cnn',['mixup','cutout']],
['randaugment',2019,'RandAugment: Practical automated data augmentation with a reduced search space','RandAugment','vision','cnn',['autoaugment']],
['giou',2019,'Generalized Intersection over Union: A Metric and A Loss for Bounding Box Regression','GIoU 손실','vision','detect',['faster-rcnn']],
['diou',2019,'Distance-IoU Loss: Faster and Better Learning for Bounding Box Regression','DIoU · CIoU 손실','vision','detect',['giou']],
['simsiam',2020,'Exploring Simple Siamese Representation Learning','SimSiam','vision','selfsup',['byol','simclr']],
['ibot',2021,'iBOT: Image BERT Pre-Training with Online Tokenizer','iBOT','vision','selfsup',['dino','beit']],
['data2vec',2022,'data2vec: A General Framework for Self-supervised Learning in Speech, Vision and Language','data2vec','vision','selfsup',['beit','wav2vec2']],
['mip-nerf',2021,'Mip-NeRF: A Multiscale Representation for Anti-Aliasing Neural Radiance Fields','Mip-NeRF','generative','threeD',['nerf']],
['instant-ngp',2022,'Instant Neural Graphics Primitives with a Multiresolution Hash Encoding','Instant-NGP','generative','threeD',['nerf','mip-nerf']],
['t2i-adapter',2023,'T2I-Adapter: Learning Adapters to Dig out More Controllable Ability for Text-to-Image Diffusion Models','T2I-Adapter','generative','diffusion',['ldm','controlnet']],
['ip-adapter',2023,'IP-Adapter: Text Compatible Image Prompt Adapter for Text-to-Image Diffusion Models','IP-Adapter','generative','diffusion',['ldm','controlnet']],
['lcm',2023,'Latent Consistency Models: Synthesizing High-Resolution Images with Few-Step Inference','Latent Consistency Model','generative','diffusion',['consistency','ldm']],
['animatediff',2023,'AnimateDiff: Animate Your Personalized Text-to-Image Diffusion Models without Specific Tuning','AnimateDiff','video','generate',['ldm','lora']],
['fastsam',2023,'Fast Segment Anything','FastSAM','vision','seg',['sam','yolov7']],
['mobile-sam',2023,'Faster Segment Anything: Towards Lightweight SAM for Mobile Applications','MobileSAM','vision','seg',['sam','distillation']],
['depth-anything-v2',2024,'Depth Anything V2','Depth Anything V2','vision','dense',['depth-anything','midas']]
];

WIKI.META = WIKI.INDEX.map(function(r){
  return { slug:r[0], year:r[1], title:r[2], ko:r[3], field:r[4], track:r[5], parents:r[6] };
});
